Description of donoho_method_snr
Home > MREdge > src > main > m > functions > osssnr > donoho_method_snr.m
donoho_method_snr
PURPOSE
SYNOPSIS
function [snr, sigma_s, sigma_n] = donoho_method_snr(x, mask)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
mad_eb MAD Mean/median absolute deviation.
This function is called by:
donoho_method_snr_multichannel
mre_snr
mre_snr_2d
SOURCE CODE
function [snr, sigma_s, sigma_n] = donoho_method_snr(x, mask)
if nargin < 2
    mask = ones(size(x));
end
mask = logical(mask);
mask_down = mask(1:2:end, 1:2:end);
signalpwr = @(x) sum(abs(x(mask)).^2)/length(x(mask));
sigpwr = signalpwr(x);
sigma_s = sqrt(sigpwr);
af = farras;
w = dwt2D(x, 1, af);
w_noise_img = w{1}{3};
sigma_n = mad_eb(w_noise_img(mask_down),1) / 0.6745;
snr = 20*log10(sigma_s / sigma_n);
% alternate equivalent
%snr = 10*log10(sigpwr / sigma_n.^2);