function parsave_rer(fname, rer_M_orig2,rer_M_moco2,rer_M_dico2,rer_M_modico2,...
            rer_A_orig2,rer_A_moco2,rer_A_dico2,rer_A_modico2)
save(fname, 'rer_M_orig2','rer_M_moco2','rer_M_dico2','rer_M_modico2',...
            'rer_A_orig2','rer_A_moco2','rer_A_dico2','rer_A_modico2')
end
