liver_1x_mean = liver_mags(1:3:end,3);
liver_2x_mean = liver_mags(2:3:end,3);
liver_4x_mean = liver_mags(3:3:end,3);
liver_1x_sd = liver_mags(1:3:end,4);
liver_2x_sd = liver_mags(2:3:end,4);
liver_4x_sd = liver_mags(3:3:end,4);
h = figure();
set(h, 'Position', [660 490 940 320]);
set(h, 'color', 'white');
c = colormap(jet(7));
c = c(1:3:end,:);
n_s = numel(liver_1x_mean);
errorbar(1:n_s, liver_1x_mean, liver_1x_sd, 'Color', c(1,:));
hold on;
errorbar(1:n_s, liver_2x_mean, liver_2x_sd, 'Color', c(2,:));
errorbar(1:n_s, liver_4x_mean, liver_4x_sd, 'Color', c(3,:));
plot(1:n_s, liver_1x_mean, 'Color', c(1,:), 'LineWidth', 2);
plot(1:n_s, liver_2x_mean, 'Color', c(2,:),  'LineWidth', 2);
plot(1:n_s, liver_4x_mean, 'Color', c(3,:), 'LineWidth', 2);
legend('1x', '2x', '4x');
xlim([1 n_s]);
title('Liver $|G^{*}|$', 'Interpreter', 'LaTeX', 'FontSize', 18);
ss = [mean(liver_1x_mean) mean(liver_2x_mean) mean(liver_4x_mean); std(liver_1x_mean) std(liver_2x_mean) std(liver_4x_mean)];
[r12, p12] = corr(liver_1x_mean,liver_2x_mean);
[r13, p13] = corr(liver_1x_mean,liver_4x_mean);