figure(); hold on; plot(amps_sorted, meanstack_norm(:,1), ...
amps_sorted, meanstack_norm(:,2), amps_sorted, meanstack_norm(:,3), ...
amps_sorted, meanstack_norm(:,4), amps_sorted, meanstack_norm(:,5) , 'LineWidth', 3);