Description of DT_SOFT
Home > MREdge > functions > wavelet > cdtw > DT_SOFT.m
DT_SOFT
PURPOSE
SYNOPSIS
function y = DT_SOFT(x, T, J)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
FSfarras Farras filters organized for the dual-tree
cplxdual3D 3D Complex Dual-Tree Discrete Wavelet Transform
dualfilt1 Kingsbury Q-filters for the dual-tree complex DWT
icplxdual3D Inverse 3D Complex Dual-Tree Discrete Wavelet Transform
This function is called by:
DT_3D_v0_51f Dualtree complex denoising
mredge_denoise_3d % function y = mredge_denoise_3d(x, info, prefs)
SOURCE CODE
function y = DT_SOFT(x, T, J)
if (nargin == 1)
    T = 0.3;
end
% Dualtree complex denoising
% with soft thresholding
[Faf, Fsf] = FSfarras;
[af, sf] = dualfilt1;
w = cplxdual3D(x,J,Faf,af);
for j = 1:J
    % loop thru subbands
    for s1 = 1:2
        for s2 = 1:2
            for s3 = 1:7
                a = w{j}{1}{s1}{s2}{s3};
                b = w{j}{2}{s1}{s2}{s3};
                C = a + 1i*b;
                % soft thresh
                c = max(abs(C) - T, 0);
                C = c./(c+T) .* C;
                %
                w{j}{1}{s1}{s2}{s3} = real(C);
                w{j}{2}{s1}{s2}{s3} = imag(C);
            end
        end
    end
end
y = icplxdual3D(w,J,Fsf,sf);