%% function mredge_reorganize_by_frequency(subdir, driving_frequencies)
%
% Part of the MREdge software package
% Created 2016 at Charite Medical University Berlin
% Private usage only. Distribution only by permission of Elastography working
% group.
%
% USAGE:
%
% For acquisitions with the all_frequencies_one_series flag,
% partitions the time series by frequency
%
% INPUTS:
%
% series_num - number of DICOM series
% data_table - data_table generated by mredge_organize_acquisition
% subdir - path of subdir that will contain this series
% time_steps - time steps in the acquisition. required for 4D conversion
%
% OUTPUTS:
%
% none

%% collect series numbers

function mredge_reorganize_by_frequency(series_number, subdir, driving_frequencies)
  NIFTI_EXTENSION = '.nii.gz';
  for f = 1:numel(driving_frequencies)
      index = (f-1)*3;
      for c = 1:3
          series_path = fullfile(subdir, num2str(series_number), num2str(index+c));
          frequency_path = fullfile(subdir, num2str(driving_frequencies(f)), num2str(c));
          if ~exist(frequency_path, 'dir')
              mkdir(frequency_path);
          end
          movefile(fullfile(series_path, mredge_filename(series_number,  num2str(index+c), NIFTI_EXTENSION)), fullfile(frequency_path, mredge_filename(driving_frequencies(f),  c, NIFTI_EXTENSION)));
      end
  end
  series_path = fullfile(subdir, num2str(series_number));
  if exist(series_path, 'dir')
      rmdir(series_path, 's');
  end
end
    
