Description of soft
Home > MREdge > functions > wavelet > ncogs_software > soft.m
soft
PURPOSE
Soft-threshold function (real or complex x)
SYNOPSIS
function y = soft(x, T)
DESCRIPTION
 Soft-threshold function (real or complex x)
 y = soft(x, T)
 Input
    x : data
    T : threshold
 If x and T are both multidimensional, then they must be of the same size.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
denC2D % Example
denR2D % Example
denS2D % Example
Example1 % Group-sparse denoising by non-convex regularization: 1D example
Example2 % Group-sparse denoising by non-convex regularization: Speech denoising
den3D_OGS_demo
denC3D_EB_soft % Example
dtdenoise_2d_undec 2D Dualtree complex denoising
SOURCE CODE
function y = soft(x, T)
% Soft-threshold function (real or complex x)
% y = soft(x, T)
% Input
%    x : data
%    T : threshold
%
% If x and T are both multidimensional, then they must be of the same size.
y = max(1 - T./abs(x), 0) .* x;
% Ivan Selesnick
% NYU-Poly
% selesi@poly.edu