Description of mredge_z_xy_noise
Home > MREdge > stats > mredge_z_xy_noise.m
mredge_z_xy_noise
PURPOSE
% function mredge_denoise(info, prefs);
SYNOPSIS
function mredge_z_xy_noise(info, prefs)
DESCRIPTION
% function mredge_denoise(info, prefs);
 Part of the MREdge software package
 Created 2016 by Eric Barnhill for Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
 USAGE:
   Deonise the complex wave field.
 INPUTS:
   info - MREdge acquisition info structure generated with mredge_acquisition_info
   prefs - MREdge preferences structure generated with mredge_prefs
 OUTPUTS:
   none
CROSS-REFERENCE INFORMATION
This function calls:
mredge_analysis_path Generates uniform analysis folder path names
mredge_filename % function filename = mredge_filename(series, component)
load_untouch_nii_eb Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
mad_est_3d
signal_power
mredge_compact_laplacian
mredge_load_mask Loads the anatomical mask image and returns as a 3D object
This function is called by:
mredge_ft_to_end % function [outputs] = mredge_ft_to_end(info, prefs);
mredge_ft_to_end_nopar % function [outputs] = mredge_ft_to_end_nopar(info, prefs);
mredge_octave % function [outputs] = mredge_octave(info, prefs);
SUBFUNCTIONS
function [FT_DIRS, STATS_SUB] = set_dirs(info, prefs)
SOURCE CODE
%% function mredge_denoise(info, prefs);
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
%
% USAGE:
%
%   Deonise the complex wave field.
%
% INPUTS:
%
%   info - MREdge acquisition info structure generated with mredge_acquisition_info
%   prefs - MREdge preferences structure generated with mredge_prefs
%
% OUTPUTS:
%
%   none
function mredge_z_xy_noise(info, prefs)
    [FT_DIRS, STATS_SUB] =set_dirs(info, prefs);
    NIF_EXT = getenv('NIFTI_EXTENSION');
    z_noise_filepath = fullfile(STATS_SUB, 'noise_est_z.csv');
    xy_noise_filepath = fullfile(STATS_SUB, 'noise_est_xy.csv');
    lap_noise_filepath = fullfile(STATS_SUB, 'noise_est_lap.csv');
    z_noise_ID = fopen(z_noise_filepath, 'w');
    xy_noise_ID = fopen(xy_noise_filepath, 'w');
    lap_noise_ID = fopen(lap_noise_filepath, 'w');
    fprintf(z_noise_ID, 'F.C, Z Noise Est \n');
    fprintf(xy_noise_ID, 'F.C, XY Noise Est \n');
    fprintf(lap_noise_ID, 'F.C, Laplacian Noise Est \n');
    for d = 1:numel(FT_DIRS);
        for f = info.driving_frequencies
            display([num2str(f), ' Hz']);
            z_noise = zeros(3,1);
            xy_noise = zeros(3,1);
            lap_noise = zeros(3,1);
            for c = 1:3
                display(num2str(c));
                mask = mredge_load_mask(info, prefs);
                wavefield_path = fullfile(FT_DIRS{d}, num2str(f), num2str(c), mredge_filename(f, c, NIF_EXT));
                wavefield_vol = load_untouch_nii_eb(wavefield_path);
                wavefield_img = wavefield_vol.img;
                z_noise(c) = z_noise_est(real(wavefield_img));
                noise = mad_est_3d(wavefield_img, mask);
                xy_noise(c) = noise ./ signal_power(wavefield_img, mask);
                lap_noise(c) = noise ./ signal_power(mredge_compact_laplacian(wavefield_img, [1 1 1], 3), mask);
            end
            z_noise_ID = fopen(z_noise_filepath, 'a');
            xy_noise_ID = fopen(xy_noise_filepath, 'a');
            lap_noise_ID = fopen(lap_noise_filepath, 'a');
            fprintf(z_noise_ID, '%d, %1.3f \n', f, norm(z_noise));
            fprintf(xy_noise_ID, '%d, %1.3f \n', f, norm(xy_noise));
            fprintf(lap_noise_ID, '%d, %1.3f\n', f, norm(lap_noise));
            fclose('all');
        end
    end
end
function [FT_DIRS, STATS_SUB] = set_dirs(info, prefs)
    if strcmp(prefs.phase_unwrap, 'gradient') == 1;
        FT_X = mredge_analysis_path(info, prefs, 'FT X');
        FT_Y = mredge_analysis_path(info, prefs, 'FT Y');
        FT_DIRS = cell(2,1);
        FT_DIRS{1} = FT_X;
        FT_DIRS{2} = FT_Y;
    else
        FT_SUB = mredge_analysis_path(info, prefs, 'FT');
        FT_DIRS = cell(1,1);
        FT_DIRS{1} = FT_SUB;
    end
    STATS_SUB = mredge_analysis_path(info, prefs, 'stats');
end