Description of mredge_laplacian_snr_stable
Home > MREdge > stats > mredge_laplacian_snr_stable.m
mredge_laplacian_snr_stable
PURPOSE
% function mredge_laplacian_snr_stable(info, prefs)
SYNOPSIS
function mredge_laplacian_snr_stable(info, prefs)
DESCRIPTION
% function mredge_laplacian_snr_stable(info, prefs)
CROSS-REFERENCE INFORMATION
This function calls:
mredge_analysis_path Generates uniform analysis folder path names
load_untouch_nii_eb Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
mad_est_3d
signal_power
mredge_compact_laplacian
mredge_load_mask Loads the anatomical mask image and returns as a 3D object
This function is called by:
SUBFUNCTIONS
function [AMP_SUB, STATS_SUB] = set_dirs(info, prefs)
function laplacian_noise(amp, filepath, mask)
SOURCE CODE
%% function mredge_laplacian_snr_stable(info, prefs)
%
% Part of the MREdge software package
% Created 2016 at Charite Medical University Berlin
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
% USAGE:
%
% Calculates the Laplacian SNR for the stable inversions of the image set.
%
% INPUTS:
%
% info - an acquisition info structure created by make_acquisition_info
% prefs - mredge preferences file
%
% OUTPUTS:
%
% none
%%
function mredge_laplacian_snr_stable(info, prefs)
    disp('Laplacian SNR');
    NIF_EXT = getenv('NIFTI_EXTENSION');
    [AMP_SUB, STATS_SUB] = set_dirs(info, prefs);
    mask = mredge_load_mask(info, prefs);
    % ALL case
    filepath = fullfile(STATS_SUB, 'laplacian_snr_single.csv');
    fID = fopen(filepath, 'w');
    amp_file = fullfile(AMP_SUB, ['ALL', NIF_EXT]);
    amp_vol = load_untouch_nii_eb(amp_file);
    laplacian_noise(amp_vol.img, filepath, mask);
    if prefs.sliding_windows
        filepath = fullfile(STATS_SUB, 'laplacian_snr_stable.csv');
        fID = fopen(filepath, 'w');
        fprintf(fID, 'Laplacian_Noise_Stable\n');
        [stable_filenames, stable_frequencies] = mredge_stable_inversions(info, prefs, 0);
        for f = 1:numel(stable_frequencies)
            amp_file = fullfile(AMP_SUB, stable_filenames{f});
            amp_vol = load_untouch_nii_eb(amp_file);
            laplacian_noise(amp_vol.img, filepath, mask);
        end
    end
end
function [AMP_SUB, STATS_SUB] = set_dirs(info, prefs)
    AMP_SUB = mredge_analysis_path(info, prefs, 'Amp');
    STATS_SUB = mredge_analysis_path(info, prefs, 'stats');
end
function laplacian_noise(amp, filepath, mask)
    amp_lap = mredge_compact_laplacian(amp, [1 1 1], 3);
    SNR_pct = signal_power(amp_lap, mask) ./ mad_est_3d(amp_lap, mask);
    SNR_db = 10 * log(SNR_pct) ./ log(10);
    fID = fopen(filepath, 'a');
    fprintf(fID, '%1.3f\n', SNR_db);
    fclose('all');
end