clear java;
f = 1:256;
dt = javaObject('dualTree.DualTree');
fb = javaObject('dualTree.FilterBanks');
ufd = javaObject('dualTree.UpFirDn');
setUpWaveletFilters;
x = dualtree(f, 1, Faf, af);
y = dt.forward1d(f, 1);
lo_matlab = x{2}{1};
lo_java = y.get(0).get(0)';
filts = Faf{1};
lo_filt = filts(:,1);
[x y z] = meshgrid(1:32,1:32,1:32);
grad = x+y+z;
l = imread([getenv('code'), 'lena.tif']);
lg = double(l) + rand(size(l)).*100;
lev = 1;
gr = [1:32];
lena = l;
lev = 1;
%denoise_time_test;
[x2 y2] = meshgrid(1:32,1:32);
grad2 = x2+y2;
wj = dt.forward2d(grad2, lev);         
%wj_d = dtd.denoise2d(wj, 0, 100);
wm = cplxdual2D(grad2, lev, Faf, af);
