%% function mredge_rename_by_frequency(subdir, driving_frequencies)
%
% Part of the MREdge software package
% Created 2016 at Charite Medical University Berlin
% Private usage only. Distribution only by permission of Elastography working
% group.
%
% USAGE:
%
% For acquisitions across different image series
% renames the series folders by frequency
%
% INPUTS:
%
% series_num - number of DICOM series
% data_table - data_table generated by mredge_organize_acquisition
% subdir - path of subdir that will contain this series
% time_steps - time steps in the acquisition. required for 4D conversion
%
% OUTPUTS:
%
% none

function mredge_rename_by_frequency(series_numbers, subdir, driving_frequencies)
  
  NIFTI_EXTENSION = '.nii.gz';
  for n = 1:numel(driving_frequencies)
    series_name = num2str(series_numbers(n));
    freq_name = num2str(driving_frequencies(n));
    % rename series folder
    movefile(fullfile(subdir, num2str(series_name)), fullfile(subdir, num2str(freq_name)));
    for c = 1:3
        % rename all the nifties. series is already renamed to freq
        series_nii_name = fullfile(subdir, num2str(driving_frequencies(n)), num2str(c), mredge_filename(series_name, c, NIFTI_EXTENSION));
        freq_nii_name = fullfile(subdir, num2str(driving_frequencies(n)), num2str(c), mredge_filename(freq_name, c, NIFTI_EXTENSION));
        series_mat_name = mredge_filename(series_name, c, '.mat');
        movefile(series_nii_name, freq_nii_name);
        if exist(series_mat_name, 'file')
            delete(series_mat_name);
        end
    end
  end
  
end
    