Description of cshift
Home > MREdge > functions > wavelet > dualtreewavelets > allcode > cshift.m
cshift
PURPOSE
Circular Shift
SYNOPSIS
function y = cshift(x, m)
DESCRIPTION
 Circular Shift
 USAGE:
    y = cshift(x, m)
 INPUT:
    x - N-point vector
    m - amount of shift
 OUTPUT:
    y - vector x will be shifed by m samples to the left
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
afb Analysis filter bank
afb_2tap Analysis filter bank
afb_stationary Analysis filter bank
sfb Synthesis filter bank
SOURCE CODE
function y = cshift(x, m)
% Circular Shift
%
% USAGE:
%    y = cshift(x, m)
% INPUT:
%    x - N-point vector
%    m - amount of shift
% OUTPUT:
%    y - vector x will be shifed by m samples to the left
%
% WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
% http://taco.poly.edu/WaveletSoftware/
N = length(x);
n = 0:N-1;
n = mod(n-m, N);
y = x(n+1);