Description of dualfilt1
Home > MREdge > functions > wavelet > dualtreewavelets > allcode > dualfilt1.m
dualfilt1
PURPOSE
Kingsbury Q-filters for the dual-tree complex DWT
SYNOPSIS
function [af, sf] = dualfilt1
DESCRIPTION
 Kingsbury Q-filters for the dual-tree complex DWT
 USAGE:
    [af, sf] = dualfilt1
 OUTPUT:
    af{i}, i = 1,2 - analysis filters for tree i
    sf{i}, i = 1,2 - synthesis filters for tree i
    note: af{2} is the reverse of af{1}
 REFERENCE:
    N. G. Kingsbury,  "A dual-tree complex wavelet
    transform with improved orthogonality and symmetry
    properties", Proceedings of the IEEE Int. Conf. on
    Image Proc. (ICIP), 2000
 See dualtree
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
DT_2D
DT_2D_DESTRIPE
DT_2D_snr
DT_2D_u
DT_HARD
DT_NNG Dualtree complex denoising
DT_OGS Dualtree complex denoising
DT_OGS_2D
DT_OGS_u Dualtree complex denoising
DT_OGS_u_diff Dualtree complex denoising
DT_OGS_u_log Dualtree complex denoising
DT_SOFT
DT_SOFT_2D
DT_SOFT_2D_ampguided
DT_SOFT_2D_killring
DT_diff
cdtw_consensus_coefficients
cdtw_spectra demo script to view spectra of CDTW components
cdtw_spectra_stationary demo script to view spectra of CDTW components
cdtw_spectra_stationary_real demo script to view spectra of CDTW components
cdwt_diff if 2d, needless to say Z is rubbish
cdwt_diff_2D if 2d, needless to say Z is rubbish
cdwt_diff_2D_stationary if 2d, needless to say Z is rubbish
cdwt_diff_3D
cdwt_diff_ogs_2D if 2d, needless to say Z is rubbish
cdwt_laplacian
dt_den_1d
dt_den_1d_stacktest
dt_time_test
dtdenoise_3d_pca
dtdenoise_z_auto_noise_est_nocrop
dtdenoise_z_nocrop
collect_dt_filters
cplxdual2D_plots cplxdual2D_plots
cplxdual2Dinterp Dual-Tree Complex 2D Discrete Wavelet Transform
cplxdual3D_interp 3D Complex Dual-Tree Discrete Wavelet Transform
cplxdual3D_plots cplxdual3D_plots
denC2D % Example
denR2D % Example
denoising_dtdwt Local Adaptive Image Denoising Algorithm
dualtree2D_plots dualtree2D_plots
dualtree3D_plots dualtree3D_plots
dualtree_eg1
normaliz_coefcalc_dual_tree
wavelet_dering_cdwt
denC3D_EB_OGS % Example
denC3D_EB_OGS_java % Example
denC3D_EB_nng
denC3D_EB_soft % Example
DT_ASG_u Dualtree complex denoising
DT_OGS_u Dualtree complex denoising
dtdenoise_2d_undec 2D Dualtree complex denoising
dtdenoise_2d_undec_guides 3D Dualtree complex denoising
testing % TESTING MODULE
SOURCE CODE
function [af, sf] = dualfilt1
% Kingsbury Q-filters for the dual-tree complex DWT
%
% USAGE:
%    [af, sf] = dualfilt1
% OUTPUT:
%    af{i}, i = 1,2 - analysis filters for tree i
%    sf{i}, i = 1,2 - synthesis filters for tree i
%    note: af{2} is the reverse of af{1}
% REFERENCE:
%    N. G. Kingsbury,  "A dual-tree complex wavelet
%    transform with improved orthogonality and symmetry
%    properties", Proceedings of the IEEE Int. Conf. on
%    Image Proc. (ICIP), 2000
% See dualtree
%
% WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
% http://taco.poly.edu/WaveletSoftware/
% These cofficients are rounded to 8 decimal places.
af{1} = [
   0.03516384000000                  0
                  0                  0
  -0.08832942000000  -0.11430184000000
   0.23389032000000                  0
   0.76027237000000   0.58751830000000
   0.58751830000000  -0.76027237000000
                  0   0.23389032000000
  -0.11430184000000   0.08832942000000
                  0                  0
                  0  -0.03516384000000
 ];
af{2} = [
                  0  -0.03516384000000
                  0                  0
  -0.11430184000000   0.08832942000000
                  0   0.23389032000000
   0.58751830000000  -0.76027237000000
   0.76027237000000   0.58751830000000
   0.23389032000000                  0
  -0.08832942000000  -0.11430184000000
                  0                  0
   0.03516384000000                  0
];
sf{1} = af{1}(end:-1:1, :);
sf{2} = af{2}(end:-1:1, :);