Description of dwt2D
Home > MREdge > functions > wavelet > dualtreewavelets > allcode > dwt2D.m
dwt2D
PURPOSE
discrete 2-D wavelet transform
SYNOPSIS
function w = dwt2D(x, J, af)
DESCRIPTION
 discrete 2-D wavelet transform
 USAGE:
   w = dwt2D(x, stages, af)
 INPUT:
   x - N by M matrix
       1) M, N are both even
       2) min(M,N) >= 2^(J-1)*length(af)
   J - number of stages
   af - analysis filters
 OUPUT:
   w - cell array of wavelet coefficients
 EXAMPLE:
   [af, sf] = farras;
   x = rand(128,64);
   J = 3;
   w = dwt2D(x,J,af);
   y = idwt2D(w,J,sf);
   err = x - y;
   max(max(abs(err)))
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
afb2D 2D Analysis Filter Bank
This function is called by:
donoho_method_snr
denS2D % Example
denoising_dwt Local Adaptive Image Denoising Algorithm
dwt2D_plots dwt2D_plots
wavelet_dering
wavelet_dering_real
SOURCE CODE
function w = dwt2D(x, J, af)
% discrete 2-D wavelet transform
%
% USAGE:
%   w = dwt2D(x, stages, af)
% INPUT:
%   x - N by M matrix
%       1) M, N are both even
%       2) min(M,N) >= 2^(J-1)*length(af)
%   J - number of stages
%   af - analysis filters
% OUPUT:
%   w - cell array of wavelet coefficients
% EXAMPLE:
%   [af, sf] = farras;
%   x = rand(128,64);
%   J = 3;
%   w = dwt2D(x,J,af);
%   y = idwt2D(w,J,sf);
%   err = x - y;
%   max(max(abs(err)))
%
% WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
% http://taco.poly.edu/WaveletSoftware/
for k = 1:J
    [x w{k}] = afb2D(x, af, af);
end
w{J+1} = x;