Description of farras
Home > MREdge > functions > wavelet > dualtreewavelets > allcode > farras.m
farras
PURPOSE
Farras nearly symmetric filters for orthogonal
SYNOPSIS
function [af, sf] = farras
DESCRIPTION
 Farras nearly symmetric filters for orthogonal
 2-channel perfect reconstruction filter bank
 USAGE:
    [af, sf] = farras
 OUTPUT:
    af - analysis filters
    sf - synthesis filters
 REFERENCE:
    A. F. Abdelnour and I. W. Selesnick.
    "Nearly symmetric orthogonal wavelet bases",
    Proc. IEEE Int. Conf. Acoust., Speech,
    Signal Processing (ICASSP), May 2001.
 See afb, dwt.
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
donoho_method_snr
denS2D % Example
denoising_dwt Local Adaptive Image Denoising Algorithm
dwt2D_plots dwt2D_plots
dwt3D_plots dwt3D_plots
plotwav1D
wavelet_dering
wavelet_gradients_stationary
SOURCE CODE
function [af, sf] = farras
% Farras nearly symmetric filters for orthogonal
% 2-channel perfect reconstruction filter bank
%
% USAGE:
%    [af, sf] = farras
% OUTPUT:
%    af - analysis filters
%    sf - synthesis filters
% REFERENCE:
%    A. F. Abdelnour and I. W. Selesnick.
%    "Nearly symmetric orthogonal wavelet bases",
%    Proc. IEEE Int. Conf. Acoust., Speech,
%    Signal Processing (ICASSP), May 2001.
% See afb, dwt.
%
% WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
% http://taco.poly.edu/WaveletSoftware/
af = [
                  0  -0.01122679215254
                  0   0.01122679215254
  -0.08838834764832   0.08838834764832
   0.08838834764832   0.08838834764832
   0.69587998903400  -0.69587998903400
   0.69587998903400   0.69587998903400
   0.08838834764832  -0.08838834764832
  -0.08838834764832  -0.08838834764832
   0.01122679215254                  0
   0.01122679215254                  0
];
sf = af(end:-1:1, :);