Description of icplxdual2D
Home > MREdge > functions > wavelet > dualtreewavelets > allcode > icplxdual2D.m
icplxdual2D
PURPOSE
Inverse Dual-Tree Complex 2D Discrete Wavelet Transform
SYNOPSIS
function y = icplxdual2D(w, J, Fsf, sf)
DESCRIPTION
 Inverse Dual-Tree Complex 2D Discrete Wavelet Transform
 USAGE:
   y = icplxdual2D(w, J, Fsf, sf)
 INPUT:
   w - wavelet coefficients
   J - number of stages
   Fsf - synthesis filters for final stage
   sf - synthesis filters for preceeding stages
 OUTPUT:
   y - output array
 See cplxdual2D
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
pm [u v] = pm(a,b)
sfb2D 2D Synthesis Filter Bank
This function is called by:
DT_2D
DT_2D_DESTRIPE
DT_2D_snr
DT_OGS_2D
DT_SOFT_2D
DT_SOFT_2D_ampguided
DT_SOFT_2D_killring
DT_diff
cdwt_diff if 2d, needless to say Z is rubbish
cdwt_diff_2D if 2d, needless to say Z is rubbish
cdwt_diff_2D_stationary if 2d, needless to say Z is rubbish
cdwt_diff_ogs_2D if 2d, needless to say Z is rubbish
collect_dt_filters
cplxdual2D_plots cplxdual2D_plots
denC2D % Example
denoising_dtdwt Local Adaptive Image Denoising Algorithm
normaliz_coefcalc_dual_tree
wavelet_dering_cdwt
SOURCE CODE
function y = icplxdual2D(w, J, Fsf, sf)
% Inverse Dual-Tree Complex 2D Discrete Wavelet Transform
%
% USAGE:
%   y = icplxdual2D(w, J, Fsf, sf)
% INPUT:
%   w - wavelet coefficients
%   J - number of stages
%   Fsf - synthesis filters for final stage
%   sf - synthesis filters for preceeding stages
% OUTPUT:
%   y - output array
% See cplxdual2D
%
% WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
% http://taco.poly.edu/WaveletSoftware/
for j = 1:J
    for m = 1:3
        [w{j}{1}{1}{m} w{j}{2}{2}{m}] = pm(w{j}{1}{1}{m},w{j}{2}{2}{m});
        [w{j}{1}{2}{m} w{j}{2}{1}{m}] = pm(w{j}{1}{2}{m},w{j}{2}{1}{m});
    end
end
y = zeros(size(w{1}{1}{1}{1})*2);
for m = 1:2
    for n = 1:2
        lo = w{J+1}{m}{n};
        for j = J:-1:2
            lo = sfb2D(lo, w{j}{m}{n}, sf{m}, sf{n});
        end
        lo = sfb2D(lo, w{1}{m}{n}, Fsf{m}, Fsf{n});
        y = y + lo;
    end
end
% normalization
y = y/2;