Description of icplxdual3D
Home > MREdge > functions > wavelet > dualtreewavelets > allcode > icplxdual3D.m
icplxdual3D
PURPOSE
Inverse 3D Complex Dual-Tree Discrete Wavelet Transform
SYNOPSIS
function y = icplxdual3D(w, J, Fsf, sf)
DESCRIPTION
 Inverse 3D Complex Dual-Tree Discrete Wavelet Transform
 USAGE:
   y = icplxdual3D(w, J, Fsf, sf)
 INPUT:
   J - number of stages
   Fsf - synthesis filter for last stage
   sf - synthesis filters for preceeding stages
 OUTPUT:
   y - output array
 See cplxdual3D
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
pm4inv [u, v, q, r] = pm4(a, b, c, d);
sfb3D 3D Synthesis Filter Bank
This function is called by:
DT_HARD
DT_NNG Dualtree complex denoising
DT_OGS Dualtree complex denoising
DT_SOFT
cdtw_consensus_coefficients
cdwt_diff_3D
cdwt_laplacian
cplxdual3D_plots cplxdual3D_plots
denC3D_EB_OGS % Example
denC3D_EB_OGS_java % Example
denC3D_EB_nng
denC3D_EB_soft % Example
SOURCE CODE
function y = icplxdual3D(w, J, Fsf, sf)
% Inverse 3D Complex Dual-Tree Discrete Wavelet Transform
%
% USAGE:
%   y = icplxdual3D(w, J, Fsf, sf)
% INPUT:
%   J - number of stages
%   Fsf - synthesis filter for last stage
%   sf - synthesis filters for preceeding stages
% OUTPUT:
%   y - output array
% See cplxdual3D
%
% WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
% http://taco.poly.edu/WaveletSoftware/
for j = 1:J
    for m = 1:7
        [w{j}{1}{1}{1}{m} w{j}{2}{2}{1}{m} w{j}{2}{1}{2}{m} w{j}{1}{2}{2}{m}] = ...
            pm4inv(w{j}{1}{1}{1}{m}, w{j}{2}{2}{1}{m}, w{j}{2}{1}{2}{m}, w{j}{1}{2}{2}{m});
         [w{j}{2}{2}{2}{m} w{j}{1}{1}{2}{m} w{j}{1}{2}{1}{m} w{j}{2}{1}{1}{m}] = ...
            pm4inv(w{j}{2}{2}{2}{m}, w{j}{1}{1}{2}{m}, w{j}{1}{2}{1}{m}, w{j}{2}{1}{1}{m});
    end
end
y = zeros(2*size(w{1}{1}{1}{1}{1}));
for m = 1:2
    for n = 1:2
        for p = 1:2
            lo = w{J+1}{m}{n}{p};
            for j = J:-1:2
                lo = sfb3D(lo, w{j}{m}{n}{p}, sf{m}, sf{n}, sf{p});
            end
            lo = sfb3D(lo, w{1}{m}{n}{p}, Fsf{m}, Fsf{n}, Fsf{p});
            y = y + lo;
        end
    end
end
% normalization
y = y/sqrt(8);