Description of idwt2D
Home > MREdge > functions > wavelet > dualtreewavelets > allcode > idwt2D.m
idwt2D
PURPOSE
Inverse 2-D Discrete Wavelet Transform
SYNOPSIS
function y = idwt2D(w, J, sf)
DESCRIPTION
 Inverse 2-D Discrete Wavelet Transform
 USAGE:
   y = idwt(w, J, sf)
 INPUT:
   w - wavelet coefficients
   J  - number of stages
   sf - synthesis filters
 OUTPUT:
   y - output array
 See dwt2D
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
sfb2D 2D Synthesis Filter Bank
This function is called by:
denS2D % Example
denoising_dwt Local Adaptive Image Denoising Algorithm
dwt2D_plots dwt2D_plots
wavelet_dering
wavelet_dering_real
SOURCE CODE
function y = idwt2D(w, J, sf)
% Inverse 2-D Discrete Wavelet Transform
%
% USAGE:
%   y = idwt(w, J, sf)
% INPUT:
%   w - wavelet coefficients
%   J  - number of stages
%   sf - synthesis filters
% OUTPUT:
%   y - output array
% See dwt2D
%
% WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
% http://taco.poly.edu/WaveletSoftware/
y = w{J+1};
for k = J:-1:1
   y = sfb2D(y, w{k}, sf, sf);
end