Description of nng
Home > MREdge > functions > wavelet > dualtreewavelets > allcode > nng.m
nng
PURPOSE
SYNOPSIS
function y = nng(x,T)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
denC3D_EB_nng
DT_ASG_u Dualtree complex denoising
dtdenoise_2d_undec_guides 3D Dualtree complex denoising
SOURCE CODE
function y = nng(x,T)
 y = ( x - T^2 ./ conj(x) ) .* (abs(x) > T);