Description of normaliz_coefcalc_dual_tree
Home > MREdge > functions > wavelet > dualtreewavelets > allcode > normaliz_coefcalc_dual_tree.m
normaliz_coefcalc_dual_tree
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
AntonB
cplxdual2D Dual-Tree Complex 2D Discrete Wavelet Transform
dualfilt1 Kingsbury Q-filters for the dual-tree complex DWT
icplxdual2D Inverse Dual-Tree Complex 2D Discrete Wavelet Transform
This function is called by:
SOURCE CODE
N = 2^9;
L = 6;
x = zeros(N);
%[Fsf,Faf] = FSfarras;
[Fsf,Faf]  = AntonB;
[sf,af] = dualfilt1;
W_zero = cplxdual2D(x, L, Faf, af);
figure(1), clf
nor = [];
for scale = 1:L
    no = length(W_zero{scale}{1}{1}{1})/2;
    for part = 1:2
    for dir = 1:2
        for dir1 = 1:3
            W = W_zero;
            W{scale}{part}{dir}{dir1}(no,no) = 1;
        y = icplxdual2D(W, L, Fsf, sf);
        nor{scale}{part}{dir}{dir1} = sqrt(sum(sum(y.^2)));
        %sqrt(sum(sum(y.^2)))
        end
    end
    end
end
save nor_dualtree nor