Description of pm
Home > MREdge > functions > wavelet > dualtreewavelets > allcode > pm.m
pm
PURPOSE
[u v] = pm(a,b)
SYNOPSIS
function [u, v] = pm(a,b)
DESCRIPTION
 [u v] = pm(a,b)
 u = (a + b)/sqrt(2);
 v = (a - b)/sqrt(2);
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cdtw_2d_stationary Stationary Version of Dual-Tree Complex 2D Discrete Wavelet Transform
dt_direc_decomp Inverse Dual-Tree Complex 2D Discrete Wavelet Transform
icdtw_2d_stationary Inverse Dual-Tree Complex 2D Discrete Wavelet Transform
cplxdual2D Dual-Tree Complex 2D Discrete Wavelet Transform
cplxdual2DOpenAll Dual-Tree Complex 2D Discrete Wavelet Transform
icplxdual2D Inverse Dual-Tree Complex 2D Discrete Wavelet Transform
icplxdual2D_diff Inverse Dual-Tree Complex 2D Discrete Wavelet Transform
cplxdual2D_u Dual-Tree Complex 2D Discrete Wavelet Transform
icplxdual2D_u Inverse Dual-Tree Complex Undecimated 2D Discrete Wavelet Transform
SOURCE CODE
function [u, v] = pm(a,b)
% [u v] = pm(a,b)
% u = (a + b)/sqrt(2);
% v = (a - b)/sqrt(2);
u = (a + b)/sqrt(2);
v = (a - b)/sqrt(2);