Description of pm4
Home > MREdge > functions > wavelet > dualtreewavelets > allcode > pm4.m
pm4
PURPOSE
[u, v, q, r] = pm4(a, b, c, d);
SYNOPSIS
function [u, v, q, r] = pm4(a, b, c, d)
DESCRIPTION
 [u, v, q, r] = pm4(a, b, c, d);
 u = (a + b - c - d)/2;
 v = (a - b + c + d)/2;
 q = (a + b - c + d)/2;
 r = (a + b + c - d)/2;
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cplxdual3D 3D Complex Dual-Tree Discrete Wavelet Transform
cplxdual3D_interp 3D Complex Dual-Tree Discrete Wavelet Transform
dualtree3D 3D Dual-Tree Discrete Wavelet Transform
cplxdual3D_u 3D Complex Dual-Tree Discrete Wavelet Transform
SOURCE CODE
function [u, v, q, r] = pm4(a, b, c, d)
% [u, v, q, r] = pm4(a, b, c, d);
% u = (a + b - c - d)/2;
% v = (a - b + c + d)/2;
% q = (a + b - c + d)/2;
% r = (a + b + c - d)/2;
u = (a - b - c - d)/2;
v = (a - b + c + d)/2;
q = (a + b - c + d)/2;
r = (a + b + c - d)/2;