Description of pm4inv
Home > MREdge > functions > wavelet > dualtreewavelets > allcode > pm4inv.m
pm4inv
PURPOSE
[u, v, q, r] = pm4(a, b, c, d);
SYNOPSIS
function [u, v, q, r] = pm4inv(a, b, c, d)
DESCRIPTION
 [u, v, q, r] = pm4(a, b, c, d);
 u = (a + b - c - d)/2;
 v = (a - b + c + d)/2;
 q = (a + b - c + d)/2;
 r = (a + b + c - d)/2;
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
icplxdual3D Inverse 3D Complex Dual-Tree Discrete Wavelet Transform
idualtree3D Inverse 3D Dual-Tree Discrete Wavelet Transform
icplxdual3D_u Inverse Dual-Tree Complex Undecimated 3D Discrete Wavelet Transform
SOURCE CODE
function [u, v, q, r] = pm4inv(a, b, c, d)
% [u, v, q, r] = pm4(a, b, c, d);
% u = (a + b - c - d)/2;
% v = (a - b + c + d)/2;
% q = (a + b - c + d)/2;
% r = (a + b + c - d)/2;
u = (a + b + c + d)/2;
v = (-a - b + c + d)/2;
q = (-a + b - c + d)/2;
r = (-a + b + c - d)/2;