Description of mredge_load_elastograms
Home > MREdge > src > main > m > file_ops > mredge_load_elastograms.m
mredge_load_elastograms
PURPOSE
Load elastograms into MATLAB
SYNOPSIS
function elastograms = mredge_load_elastograms(info, prefs)
DESCRIPTION
 Load elastograms into MATLAB
 USAGE:
   elastograms  = mredge_load_elastograms(info, prefs)
 INPUTS:
   info - MREdge acquisition info structure generated with mredge_acquisition_info
   prefs - MREdge preferences structure generated with mredge_prefs
 OUTPUTS:
   cell array of all elastograms of the inversion type indicated in prefs
 Part of the MREdge software package
 Copyright (c) 2018 Eric Barnhill. All Rights Reserved
 So that we can vouch for results,
 this code is source-available but not open source.
 Please contact Eric Barnhill at ericbarnhill@protonmail.ch
 for permission to make modifications.
CROSS-REFERENCE INFORMATION
This function calls:
mredge_analysis_path Generates uniform analysis folder path names
mredge_dir Returns portions of MATLAB's dir command that contain files
This function is called by:
mredge Base function for the processing and analysis of MRE data
SOURCE CODE
function elastograms = mredge_load_elastograms(info, prefs)
% Load elastograms into MATLAB
%
% USAGE:
%
%   elastograms  = mredge_load_elastograms(info, prefs)
%
% INPUTS:
%
%   info - MREdge acquisition info structure generated with mredge_acquisition_info
%   prefs - MREdge preferences structure generated with mredge_prefs
%
% OUTPUTS:
%
%   cell array of all elastograms of the inversion type indicated in prefs
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
elastograms = cell(0);
if strcmpi(prefs.inversion_strategy, 'mdev')
    params = {'absg', 'phi'};
else
    params  = {prefs.inversion_strategy};
end
for p = 1:numel(params)
    elastogram_path = cell2str(fullfile(mredge_analysis_path(info, prefs, p)));
    elastogram_dir = mredge_dir(elastogram_path);
    tally = 1;
    for n = 1:numel(elastogram_dir)
        filename = elastogram_dir(n).name;
        if strcmpi(filename((end-3):end), '.nii')
            vol = load_untouch_nii(fullfile(elastogram_path, filename));
            elastograms{tally} = vol.img;
            tally = tally + 1;
        end
    end
end