Description of mredge_coreg_param_to_mni_sliding
Home > MREdge > neuro > mredge_coreg_param_to_mni_sliding.m
mredge_coreg_param_to_mni_sliding
PURPOSE
% function coreg_param_to_mni_sliding(info, param)
SYNOPSIS
function mredge_coreg_param_to_mni_sliding(info_an, prefs, param)
DESCRIPTION
% function coreg_param_to_mni_sliding(info, param)
CROSS-REFERENCE INFORMATION
This function calls:
mredge_analysis_path Generates uniform analysis folder path names
load_untouch_nii_eb Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
This function is called by:
mredge_brain_analysis_sliding % function mredge_brain_analysis_sliding(info, prefs);
SUBFUNCTIONS
function [MAG_SUB, PARAM_SUB] = set_dirs(info_an, prefs, param)
function coreg_param_to_mni(mag_file, param_file, voxel_spacing)
SOURCE CODE
%% function coreg_param_to_mni_sliding(info, param)
%
% Part of the MREdge software package
% Created 2016 at Charite Medical University Berlin
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
% USAGE:
%
% Coregisters a parameter map to MNI space using the deformation map
% from the averaged magnitude. Requires calling of mredge_average_magnitude
% and mredge_avg_mag_to_mni first.
%
% INPUTS:
%
% info - an acquisition info structure created by make_acquisition_info
% param - Name of elasticity parameter: 'absg', 'phi', 'c', 'a'
%
% OUTPUTS:
%
% none
%%
function mredge_coreg_param_to_mni_sliding(info_an, prefs, param)
    [MAG_SUB, PARAM_SUB] = set_dirs(info_an, prefs, param);
    yfile_zip = fullfile(MAG_SUB, 'y_Avg_Magnitude.nii.gz');
    yfile_unzip = yfile_zip(1:end-3);
    if exist(yfile_zip, 'file')
        gunzip(yfile_zip);
    end
     [stable_filenames, stable_frequencies] = mredge_invert_sliding(info_an, prefs, 0);
    for f = 1:numel(stable_frequencies)
        disp(['Coreg to MNI: ',num2str(stable_frequencies(f)), 'Hz']);
        tic
        freq_file = fullfile(PARAM_SUB, stable_filenames{f});
        coreg_param_to_mni(yfile_unzip, freq_file, info_an.voxel_spacing*1000);
        toc
    end
end
function [MAG_SUB, PARAM_SUB] = set_dirs(info_an, prefs, param)
    MAG_SUB = mredge_analysis_path(info_an, prefs, 'Magnitude');
    PARAM_SUB = mredge_analysis_path(info_an, prefs, param);
end
function coreg_param_to_mni(mag_file, param_file, voxel_spacing)
    spm('defaults','fmri');
    spm_jobman('initcfg');
    matlabbatch{1}.spm.spatial.normalise.write.subj.def = {mag_file};
    matlabbatch{1}.spm.spatial.normalise.write.subj.resample = {param_file};
    matlabbatch{1}.spm.spatial.normalise.write.woptions.bb = [-78 -112 -70
        78 76 85];
    matlabbatch{1}.spm.spatial.normalise.write.woptions.vox = voxel_spacing;
    matlabbatch{1}.spm.spatial.normalise.write.woptions.interp = 4;
    matlabbatch{1}.spm.spatial.normalise.write.woptions.prefix = 'w';
    spm_jobman('run',matlabbatch);
     % kludge to remove nans
    [a, b, c] = fileparts(param_file);
    w_file = [a, '/', 'w', b, c];
    w_vol = load_untouch_nii_eb(w_file);
    w_vol.img(isnan(w_vol.img)) = 0;
    save_untouch_nii_eb(w_vol, w_file);
end