Description of mredge_label_param_map_sliding
Home > MREdge > neuro > mredge_label_param_map_sliding.m
mredge_label_param_map_sliding
PURPOSE
% function stats = mredge_label_param_map_sliding(info, param)
SYNOPSIS
function mredge_label_param_map_sliding(info_an, prefs, param)
DESCRIPTION
% function stats = mredge_label_param_map_sliding(info, param)
CROSS-REFERENCE INFORMATION
This function calls:
mredge_analysis_path Generates uniform analysis folder path names
load_untouch_nii_eb Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
This function is called by:
mredge_brain_analysis_sliding % function mredge_brain_analysis_sliding(info, prefs);
SUBFUNCTIONS
function [PARAM_SUB, STATS_SUB] = set_dirs(info_an, prefs, param)
function label_param_map(STATS_SUB, param, tpm_image_path, param_file_path, noise_thresh, f)
SOURCE CODE
%% function stats = mredge_label_param_map_sliding(info, param)
%
% Part of the MREdge software package
% Created 2016 at Charite Medical University Berlin
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
% USAGE:
%
% Applies label volume to parameter map. Returns statistics for each
% labelled anatomical region.
%
% INPUTS:
%
% info - an acquisition info structure created by make_acquisition_info
% param - Name of elasticity parameter: 'absg', 'phi', 'c', 'a'
%
% OUTPUTS:
%
% none
%%
function mredge_label_param_map_sliding(info_an, prefs, param)
    [PARAM_SUB, STATS_SUB] = set_dirs(info_an, prefs, param);
    tpm_image_path = fullfile(spm('Dir'), 'tpm', 'labels_Neuromorphometrics.nii');
    ABSG_NOISE_THRESH = prefs.abs_g_noise_thresh;
    if strcmp(param, 'Abs_G') || strcmp(param, 'SFWI') || strcmp(param, 'HELM')
        noise_thresh = ABSG_NOISE_THRESH;
    else
        noise_thresh = eps;
    end
    [stable_filenames, stable_frequencies] = mredge_invert_sliding(info_an, prefs, 0);
    for f = 1:numel(stable_frequencies)
        disp(['Label Param Map: ',num2str(stable_frequencies(f)), 'Hz']);
        tic
        freq_file = fullfile(PARAM_SUB, ['rw', stable_filenames{f}]);
        label_param_map(STATS_SUB, param, tpm_image_path, freq_file, noise_thresh, f);
        toc
    end
end
function [PARAM_SUB, STATS_SUB] = set_dirs(info_an, prefs, param)
    PARAM_SUB =  mredge_analysis_path(info_an, prefs, param);
    STATS_SUB = mredge_analysis_path(info_an, prefs, 'stats');
end
function label_param_map(STATS_SUB, param, tpm_image_path, param_file_path, noise_thresh, f)
    param_coreg_vol = load_untouch_nii_eb(param_file_path);
    param_img = param_coreg_vol.img;
    labels_vol = load_untouch_nii_eb(tpm_image_path);
    labels_img = labels_vol.img;
    labels_file = importdata('labels_Neuromorphometrics.xls');
    label_nums = labels_file.data;
    labels = labels_file.textdata(:,2);
    label_stats_path = fullfile(STATS_SUB, ['label_stats_stable_', param, '.csv']);
    num_labels = numel(label_nums);
    WM = 'White Matter';
    wm_sum = 0;
    wm_tally = 0;
    wm_path = fullfile(STATS_SUB, ['wm_stats_stable_', param, '.csv']);
    for n = 1:num_labels
        label_num = label_nums(n);
        label_voxels = labels_img == label_num;
        param_label_voxels = param_img(label_voxels);
        param_values = param_label_voxels(~isnan(param_label_voxels));
        param_values = param_values(param_values > noise_thresh);
        stats(n).label = labels{n}; %#ok<*AGROW>
        stats(n).num_voxels = numel(param_values);
        stats(n).mean = mean(param_values);
        stats(n).median = median(param_values);
        stats(n).std = std(param_values);
        stats(n).min = min(param_values);
        stats(n).max = max(param_values);
    end
    if nargin < 6
        label_fileID = fopen(label_stats_path, 'w');
        fprintf(label_fileID, 'MDEV \n');
    else
        label_fileID = fopen(label_stats_path, 'a');
        fprintf(label_fileID, '%.3d \n', f);
    end
    fprintf(label_fileID, '%s\n', 'Label,NumVoxels,Mean,Median,Std,Min,Max');
    for n = 1:numel(stats)
        if stats(n).num_voxels > 0
            fprintf(label_fileID, '%s,%d,%1.3f,%1.3f,%1.3f,%1.3f,%1.3f\n', stats(n).label, stats(n).num_voxels, stats(n).mean, stats(n).median, stats(n).std, stats(n).min, stats(n).max);
            is_wm = strfind(stats(n).label,WM);
            if any(is_wm) && stats(n).mean > noise_thresh % if this is white matter and not NaN
                wm_sum = wm_sum + stats(n).mean;
                wm_tally = wm_tally + 1;
            end
        end
    end
    if nargin < 6
        label_fileID = fopen(wm_path, 'w');
        fprintf(label_fileID, '%s,%1.3f\n', 'ALL', wm_sum/wm_tally);
    else
        label_fileID = fopen(wm_path, 'a');
        fprintf(label_fileID, '%s,%d,%1.3f\n', num2str(f), wm_tally, wm_sum/wm_tally);
    end
    fclose('all');
end