Description of mredge_brain_analysis_sliding
Home > MREdge > neuro > mredge_brain_analysis_sliding.m
mredge_brain_analysis_sliding
PURPOSE
% function mredge_brain_analysis_sliding(info, prefs);
SYNOPSIS
function mredge_brain_analysis_sliding(info_mag, info_an, prefs)
DESCRIPTION
% function mredge_brain_analysis_sliding(info, prefs);
 Part of the MREdge software package
 Created 2016 by Eric Barnhill for Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
 USAGE:
   coregisters and labels brain results
   If you use this method cite
   [fehlner ref to come]
 INPUTS:
   info - MREdge acquisition info structure generated with mredge_acquisition_info
   prefs - MREdge preferences structure generated with mredge_prefs
 OUTPUTS:
   none
CROSS-REFERENCE INFORMATION
This function calls:
mredge_avg_mag_to_mni Co-registers magnitude image to MNI space. The deformation map is then used to co-register all elasticity maps.
mredge_coreg_param_to_mni_sliding % function coreg_param_to_mni_sliding(info, param)
mredge_label_param_map_sliding % function stats = mredge_label_param_map_sliding(info, param)
mredge_mni_to_label_space_sliding % function mredge_mni_to_label_space_sliding(info, param)
This function is called by:
SUBFUNCTIONS
function brain_analysis_sliding(info_an, prefs, param)
SOURCE CODE
function mredge_brain_analysis_sliding(info_mag, info_an, prefs)
%% function mredge_brain_analysis_sliding(info, prefs);
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
%
% USAGE:
%
%   coregisters and labels brain results
%
%   If you use this method cite
%
%   [fehlner ref to come]
%
% INPUTS:
%
%   info - MREdge acquisition info structure generated with mredge_acquisition_info
%   prefs - MREdge preferences structure generated with mredge_prefs
%
% OUTPUTS:
%
%   none
    if nargin == 2
        prefs = info_an;
        info_an = info_mag;
    end
    mredge_avg_mag_to_mni(info_mag, prefs);
    if strcmpi(prefs.inversion_strategy, 'MDEV') == 1
        brain_analysis_sliding(info_an, prefs, 'Abs_G');
        brain_analysis_sliding(info_an, prefs, 'amp');
    end
    if strcmpi(prefs.inversion_strategy, 'SFWI') == 1
        brain_analysis_sliding(info_an, prefs, 'SFWI');
    end
end
function brain_analysis_sliding(info_an, prefs, param)
    mredge_coreg_param_to_mni_sliding(info_an, prefs, param);
    mredge_mni_to_label_space_sliding(info_an, prefs, param);
    mredge_label_param_map_sliding(info_an, prefs, param);
end