Description of mredge_brain_analysis
Home > MREdge > neuro > mredge_brain_analysis.m
mredge_brain_analysis
PURPOSE
Provides co-registration, segmentation and analysis of brain MRE data. Requires SPM12.
SYNOPSIS
function mredge_brain_analysis(info, prefs, freq_indices)
DESCRIPTION
 Provides co-registration, segmentation and analysis of brain MRE data. Requires SPM12.
 USAGE:
   coregisters and labels brain results
   If you use this method cite:
   [paper in revision]
 INPUTS:
   info - MREdge acquisition info structure generated with mredge_acquisition_info
   prefs - MREdge preferences structure generated with mredge_prefs
 OUTPUTS:
   none
 SEE ALSO:
   mredge_avg_mag_to_mni, mredge_coreg_param_to_mni,
   mredge_mni_to_label_space, mredge_label_param_map
 Part of the MREdge software package
 Created 2016 by Eric Barnhill for Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
CROSS-REFERENCE INFORMATION
This function calls:
mredge_avg_mag_to_mni Co-registers magnitude image to MNI space. The deformation map is then used to co-register all elasticity maps.
mredge_coreg_param_to_mni Coregisters a parameter map to MNI space using the deformation map from the averaged magnitude.
mredge_label_param_map Labels paramater map results and produces statistics for brain anatomical regions.
mredge_mni_to_label_space Transforms MNI space results to SPM label space
This function is called by:
mredge_ft_to_end % function [outputs] = mredge_ft_to_end(info, prefs);
mredge_ft_to_end_nopar % function [outputs] = mredge_ft_to_end_nopar(info, prefs);
mredge_invert_and_stats Performs wave inversion and inversion-related statistical measures
mredge_invert_to_end
mredge_octave % function [outputs] = mredge_octave(info, prefs);
SOURCE CODE
function mredge_brain_analysis(info, prefs, freq_indices)
% Provides co-registration, segmentation and analysis of brain MRE data. Requires SPM12.
%
% USAGE:
%
%   coregisters and labels brain results
%
%   If you use this method cite:
%
%   [paper in revision]
%
% INPUTS:
%
%   info - MREdge acquisition info structure generated with mredge_acquisition_info
%   prefs - MREdge preferences structure generated with mredge_prefs
%
% OUTPUTS:
%
%   none
%
% SEE ALSO:
%
%   mredge_avg_mag_to_mni, mredge_coreg_param_to_mni,
%   mredge_mni_to_label_space, mredge_label_param_map
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
mredge_avg_mag_to_mni(info, prefs);
if strcmpi(prefs.inversion_strategy, 'mdev')
    params = {'absg', 'phi'};
else
    params  = {prefs.inversion_strategy};
end
for p = 1:numel(params)
    mredge_coreg_param_to_mni(info, prefs, param, freq_indices);
    mredge_mni_to_label_space(info, prefs, param, freq_indices);
    mredge_label_param_map(info, prefs, param, freq_indices);
end