Description of mredge_mni_to_label_space
Home > MREdge > neuro > mredge_mni_to_label_space.m
mredge_mni_to_label_space
PURPOSE
Transforms MNI space results to SPM label space
SYNOPSIS
function mredge_mni_to_label_space(info, prefs, param, freq_indices)
DESCRIPTION
 Transforms MNI space results to SPM label space
 INPUTS:
   info - an acquisition info structure created by make_acquisition_info
   prefs - MREdge prefs struct
   param - elasticity parameter
   freq_indices - indices of driving frequencies
 OUTPUTS:
   none
 SEE ALSO:
   mredge_brain_analysis, mredge_avg_mag_to_mni,
   mredge_coreg_param_to_mni, mredge_label_param_map
 Part of the MREdge software package
 Created 2016 at Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
CROSS-REFERENCE INFORMATION
This function calls:
mredge_analysis_path Generates uniform analysis folder path names
mredge_freq_indices_to_filename
mredge_unzip_if_zip Unzips nifti if it is zipped. For navigation between SPM, FSL and other packages.
This function is called by:
mredge_brain_analysis Provides co-registration, segmentation and analysis of brain MRE data. Requires SPM12.
SUBFUNCTIONS
function mni_to_label_space(tpm_path, unzip_path)
SOURCE CODE
function mredge_mni_to_label_space(info, prefs, param, freq_indices)
% Transforms MNI space results to SPM label space
%
% INPUTS:
%
%   info - an acquisition info structure created by make_acquisition_info
%   prefs - MREdge prefs struct
%   param - elasticity parameter
%   freq_indices - indices of driving frequencies
%
% OUTPUTS:
%
%   none
%
% SEE ALSO:
%
%   mredge_brain_analysis, mredge_avg_mag_to_mni,
%   mredge_coreg_param_to_mni, mredge_label_param_map
%
% Part of the MREdge software package
% Created 2016 at Charite Medical University Berlin
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
PARAM_SUB =  mredge_analysis_path(info, prefs, param);
tpm_path = fullfile(spm('Dir'), 'tpm', 'labels_Neuromorphometrics.nii');
all_file = mredge_unzip_if_zip(fullfile(PARAM_SUB, ['w', mredge_freq_indices_to_filename(info,prefs,freq_indices)]));
mni_to_label_space(tpm_path, all_file)
end
function mni_to_label_space(tpm_path, unzip_path)
    spm('defaults','fmri');
    spm_jobman('initcfg');
    matlabbatch{1}.spm.spatial.coreg.write.ref = {tpm_path};
    matlabbatch{1}.spm.spatial.coreg.write.source = {unzip_path};
    matlabbatch{1}.spm.spatial.coreg.write.roptions.interp = 4;
    matlabbatch{1}.spm.spatial.coreg.write.roptions.wrap = [0 0 0];
    matlabbatch{1}.spm.spatial.coreg.write.roptions.mask = 0;
    matlabbatch{1}.spm.spatial.coreg.write.roptions.prefix = 'r';
    spm_jobman('run',matlabbatch');
end