%% function mredge_dicom_to_nii(series_num, data_table, subdir, time_steps)
%
% Part of the MREdge software package
% Created 2016 at Charite Medical University Berlin
% Private usage only. Distribution only by permission of Elastography working
% group.
%
% USAGE:
%
% Organizes DICOM slices into nifti files, guided by acquisition info object, and
% divides into folders by time series.
%
% INPUTS:
%
% series_num - number of DICOM series
% data_table - data_table generated by mredge_organize_acquisition
% subdir - path of subdir that will contain this series
% is time_series - sorts niftis by time series, and converts to 4D
% time_steps - time steps in the acquisition. required for 4D conversion
%
% OUTPUTS:
%
% none

%% collect series numbers

function mredge_dicom_to_nii(series_num, data_table, subdir, is_time_series, info)

display(['DICOM to .nii, Series ', num2str(series_num)])

series_numbers = data_table{1};
file_names = data_table{3};

current_series = find(series_numbers == series_num);
num_current_series = numel(current_series);
files_cat = file_names(current_series(1),:);
for n = 2:num_current_series
    files_cat = char(files_cat, file_names(current_series(n),:));
end
assignin('base', ['files_cat_',num2str(series_num)], files_cat);
hdr_table = spm_dicom_headers(files_cat);
spm_dicom_convert(hdr_table, 'all', 'flat', 'nii');
series_subdir = fullfile(subdir, num2str(series_num));
if ~exist(series_subdir, 'dir')
    mkdir(series_subdir);
end
movefile('*.nii', series_subdir);

dicom_dir = (fullfile(subdir, 'DICOM'));
if ~exist(dicom_dir, 'dir')
    mkdir(dicom_dir)
end
assignin('base', 'file_names', file_names);
for n = 1:numel(hdr_table)
    movefile(hdr_table{n}.Filename, dicom_dir);
end

if nargin > 3
  if is_time_series == 1
    mredge_sort_by_time_series(subdir, series_num, info);
  end
end
    

