Description of mredge_distortion_correction_raw
Home > MREdge > src > main > m > mredge_distortion_correction_raw.m
mredge_distortion_correction_raw
PURPOSE
Performs distortion correction on raw MR signal data
SYNOPSIS
function mredge_distortion_correction_raw(info)
DESCRIPTION
 Performs distortion correction on raw MR signal data
 INPUTS:
   info - an acquisition info structure created with make_acquisition_info
   prefs - a preference file structure created with mredge_prefs
 OUTPUTS:
   none
 NOTE:
   Acquisition must have fieldmap time series, specified in the info struct.
   Slices must have been acquired with synchronized phases (i.e. not newer
   continuous-motion protocols).
 SEE ALSO:
   mredge_distortion_correction, mredge_distortion_correction_ft
 Part of the MREdge software package
 Copyright (c) 2018 Eric Barnhill. All Rights Reserved
 So that we can vouch for results,
 this code is source-available but not open source.
 Please contact Eric Barnhill at ericbarnhill@protonmail.ch
 for permission to make modifications.
CROSS-REFERENCE INFORMATION
This function calls:
mredge_remove_nifti_extension Strips file extension from a nifti file, to allow alteration of filenames
mredge_unzip_if_zip Unzips nifti if it is zipped. For navigation between SPM, FSL and other packages
mredge_3d_to_4d Convert cell array of 3D nii files to single 4D nii file.
mredge_pm2ri Converts phase and magnitude data to real and imaginary data for processing of complex MR signal
mredge_ri2pm Converts real and imagianry data to phase and magnitude
This function is called by:
mredge_distortion_correction Correct for distortion in the MRE acquisition using FSL or SPM libraries
SUBFUNCTIONS
function apply_topup(path, TOPUP_RESULTS)
SOURCE CODE
function mredge_distortion_correction_raw(info)
% Performs distortion correction on raw MR signal data
%
% INPUTS:
%
%   info - an acquisition info structure created with make_acquisition_info
%   prefs - a preference file structure created with mredge_prefs
%
% OUTPUTS:
%
%   none
%
% NOTE:
%
%   Acquisition must have fieldmap time series, specified in the info struct.
%   Slices must have been acquired with synchronized phases (i.e. not newer
%   continuous-motion protocols).
%
% SEE ALSO:
%
%   mredge_distortion_correction, mredge_distortion_correction_ft
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
disp('MREdge Distortion Correction');
if ~ info.ds.logical(info.ds.enum.fieldmap)
    disp('MREdge ERROR: No fieldmap directory for this acquisition.');
    return
end
fieldmap_dir = cell2str(info.ds.list(info.ds.enum.fieldmap));
cd(fieldmap_dir);
% Select DICOM files, convert and rename
% Files for Distortion correction (taken from separate 10-second scans)
% should only be one .nii in each Fieldmap series folder
RL_series = info.fieldmap(1);
LR_series = info.fieldmap(2);
RL_nifti_name = dir(fullfile(fieldmap_dir, [num2str(RL_series), '.nii']));
LR_nifti_name = dir(fullfile(fieldmap_dir, [num2str(LR_series), '.nii']));
cell_array{1} = fullfile(fieldmap_dir, RL_nifti_name.name);
cell_array{2} = fullfile(fieldmap_dir, LR_nifti_name.name);
name_4d = fullfile(fieldmap_dir, 'Distortion_Map_4d.nii');
mredge_3d_to_4d(cell_array, name_4d);
disp('Prepping...');
topup_command = ['fsl5.0-topup --imain=', name_4d, ' --datain=', getenv('TOPUP_PARAMS'), ' --config=b02b0.cnf --out=topup_results --fout=topup_field --iout=topup_field_map'];
system(topup_command);
TOPUP_RESULTS = fullfile(fieldmap_dir, 'topup_results');
mredge_pm2ri(info);
for subdir = info.ds.subdirs_comps_files
    apply_topup(cell2str(fullfile(info.ds.list(info.ds.enum.real), subdir)), TOPUP_RESULTS);
    apply_topup(cell2str(fullfile(info.ds.list(info.ds.enum.imaginary), subdir)), TOPUP_RESULTS);
end
mredge_ri2pm(info);
end
function apply_topup(path, TOPUP_RESULTS)
    path_temp = [mredge_remove_nifti_extension(path) '_temp.nii.gz'];
    copyfile(path, path_temp);
    apply_topup_command = ['fsl5.0-applytopup --imain=', path_temp, ' --inindex=1 --datain=', getenv('TOPUP_PARAMS') ' --topup=', TOPUP_RESULTS, ' --method=jac --interp=spline --out=', path];
    system(apply_topup_command);
    mredge_unzip_if_zip(path);
    delete(path_temp);
end