Description of mredge_temporal_ft
Home > MREdge > src > main > m > mredge_temporal_ft.m
mredge_temporal_ft
PURPOSE
Temporally Fourier-transforms the complex wave field
SYNOPSIS
function mredge_temporal_ft(info, prefs)
DESCRIPTION
 Temporally Fourier-transforms the complex wave field
 INPUTS:
   info - MREdge acquisition info structure generated with mredge_acquisition_info
   prefs - MREdge preferences structure generated with mredge_prefs
 OUTPUTS:
   none
 Part of the MREdge software package
 Copyright (c) 2018 Eric Barnhill. All Rights Reserved
 So that we can vouch for results,
 this code is source-available but not open source.
 Please contact Eric Barnhill at ericbarnhill@protonmail.ch
 for permission to make modifications.
CROSS-REFERENCE INFORMATION
This function calls:
mredge_analysis_path Generates uniform analysis folder path names
This function is called by:
mredge Base function for the processing and analysis of MRE data
mredge_ft_to_end Calls mredge inversion pipeline, but skips mredge preprocessing
SOURCE CODE
function mredge_temporal_ft(info, prefs)
% Temporally Fourier-transforms the complex wave field
%
% INPUTS:
%
%   info - MREdge acquisition info structure generated with mredge_acquisition_info
%   prefs - MREdge preferences structure generated with mredge_prefs
%
% OUTPUTS:
%
%   none
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
for subdir = info.ds.subdirs_comps_files
    time_series_path = cell2str(fullfile(info.ds.list(info.ds.enum.phase), subdir));
    time_series_vol = load_untouch_nii_eb(time_series_path);
    % make dummy complex 3d volume
    ft_vol = time_series_vol;
    ft_vol.hdr.dime.datatype = 32;
    ft_vol.hdr.dime.dim(1) = 3;
    ft_vol.hdr.dime.dim(5) = 1;
    % call functionality here
    phase_ft = fft(double(time_series_vol.img), [],  4);
    ft_vol.img = phase_ft(:,:,:,2);
    save_path = fullfile(mredge_analysis_path(info, prefs, 'FT'), cell2str(subdir));
    save_untouch_nii_eb(ft_vol, save_path);
end