Description of mredge
Home > MREdge > src > main > m > mredge.m
mredge
PURPOSE
Base function for the processing and analysis of MRE data
SYNOPSIS
function outputs = mredge(info, prefs)
DESCRIPTION
 Base function for the processing and analysis of MRE data
 INPUTS:
   info - MREdge acquisition info structure generated with mredge_acquisition_info
   prefs - MREdge preferences structure generated with mredge_prefs
 OUTPUTS:
   returns a structure containing outputs as specified by prefs
 EXAMPLE USAGE:
   local_data_path = pwd; % copy raw data locally before running MREdge!
   info = mredge_info('path', local_data_path, 'magnitude', 2, 'phase',
   3);
   prefs = mredge_prefs('outputs.elastograms', 1);
   elastograms = mredge(info, prefs);
 Part of the MREdge software package
 Copyright (c) 2018 Eric Barnhill. All Rights Reserved
 So that we can vouch for results,
 this code is source-available but not open source.
 Please contact Eric Barnhill at ericbarnhill@protonmail.ch
 for permission to make modifications.
CROSS-REFERENCE INFORMATION
This function calls:
mredge_clean_acquisition_folder Cleans all processing files from local acquisition folder, leaving only DICOMs.
mredge_dicom_to_nifti Converts raw DICOM files into NIfTI objects, which are used for all MREdge processing
mredge_load_FT_as_5d Load Fourier-transformed wavefield into MATLAB
mredge_load_amplitudes Load amplitude maps into MATLAB
mredge_load_elastograms Load elastograms into MATLAB
mredge_organize_acquisition Creates nested folder structure for NIfTI files
mredge_average_magnitude Creates a single, averaged t2 magnitude map from an MRE acquisition, the preferred volume to use for co-registration and segmentation.
mredge_bandpass Applies highpass and lowpass butterworth filters if they are set in prefs
mredge_denoise Denoise Fourier-transformed wavefield
mredge_denoise_raw Denoises raw complex data prior to phase unwrapping
mredge_distortion_correction Correct for distortion in the MRE acquisition using FSL or SPM libraries
mredge_invert_and_stats Performs wave inversion and inversion-related statistical measures
mredge_motion_correction Performs motion correction on raw MRE acquisitions, using FSL or SPM
mredge_phase_unwrap Applies phase unwrapping methods
mredge_remove_divergence Numerical divergence removal of the wave field
mredge_remove_ipds Removes interslice phase discontinuities
mredge_set_environment Set environment variables for MREdge
mredge_slice_align Dejitters slices using adaptation of Nikolova et al 2001 dejitter algorithm
mredge_temporal_ft Temporally Fourier-transforms the complex wave field
mredge_snr Calculates SNR maps and records SNR values in stats folder
This function is called by:
SOURCE CODE
function outputs = mredge(info, prefs)
% Base function for the processing and analysis of MRE data
%
% INPUTS:
%
%   info - MREdge acquisition info structure generated with mredge_acquisition_info
%   prefs - MREdge preferences structure generated with mredge_prefs
%
% OUTPUTS:
%
%   returns a structure containing outputs as specified by prefs
%
% EXAMPLE USAGE:
%
%   local_data_path = pwd; % copy raw data locally before running MREdge!
%   info = mredge_info('path', local_data_path, 'magnitude', 2, 'phase',
%   3);
%   prefs = mredge_prefs('outputs.elastograms', 1);
%   elastograms = mredge(info, prefs);
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%% prepare data
a = tic;
if isempty(getenv('MREDGE_ENV_SET'))
    mredge_set_environment;
end
mredge_clean_acquisition_folder(info);
mredge_dicom_to_nifti(info);
mredge_organize_acquisition(info);
mredge_average_magnitude(info, prefs);
save(fullfile(info.path, 'infoprefs.mat'), 'info', 'prefs');
% check for compabitility routines
if strcmp(prefs.compat, 'cisnmo')
    outputs = mredge_compat_cisnmo(info, prefs);
else
    %% preprocess
    if prefs.distortion_correction && strcmpi(prefs.dico_method, 'raw')
        mredge_distortion_correction(info, prefs);
    end
    if prefs.motion_correction
        mredge_motion_correction(info, prefs);
    end
    if prefs.denoise_raw
        mredge_denoise_raw(info, prefs);
    end
    if ~strcmp(prefs.phase_unwrap, 'none')
        mredge_phase_unwrap(info, prefs);
    end
    mredge_temporal_ft(info, prefs);
    if prefs.remove_ipds
        mredge_slice_align(info,prefs);
        mredge_remove_ipds(info, prefs);
    end
    if ~prefs.denoise_raw && ~strcmpi(prefs.denoise_strategy, 'none')
        mredge_denoise(info, prefs);
    end
    if ~strcmpi(prefs.curl_strategy, 'none')
        mredge_remove_divergence(info, prefs);
    end
    if prefs.highpass || prefs.lowpass
        mredge_bandpass(info, prefs);
    end
    mredge_snr(info, prefs);
    %% invert and generate outputs
    mredge_invert_and_stats(info,prefs)
    % set outputs
    outputs = [];
    if prefs.outputs.elastograms
        outputs.elastograms = mredge_load_elastograms(info, prefs);
    end
    if prefs.outputs.amplitudes
        outputs.amplitudes = mredge_load_amplitudes(info, prefs);
    end
    if prefs.outputs.wavefields
        outputs.wavefields = mredge_load_FT_as_5d(info, prefs);
    end
end
disp(['Total MREdge time: ' num2str(toc(a)) ]);
end