Description of mredge_distortion_correction
Home > MREdge > src > main > m > mredge_distortion_correction.m
mredge_distortion_correction
PURPOSE
Correct for distortion in the MRE acquisition using FSL or SPM libraries
SYNOPSIS
function mredge_distortion_correction(info, prefs)
DESCRIPTION
 Correct for distortion in the MRE acquisition using FSL or SPM libraries
 INPUTS:
   info - an acquisition info structure created with make_acquisition_info
   prefs - a preference file structure created with mredge_prefs
 OUTPUTS:
   none
 SEE ALSO:
   mredge_distortion_correction_raw, mredge_distortion_correction_ft
 NOTE:
   This requires fieldmaps in the acquisition, specified in the info
   struct.
   At present the FT distortion correction is not recommended.
 Part of the MREdge software package
 Copyright (c) 2018 Eric Barnhill. All Rights Reserved
 So that we can vouch for results,
 this code is source-available but not open source.
 Please contact Eric Barnhill at ericbarnhill@protonmail.ch
 for permission to make modifications.
CROSS-REFERENCE INFORMATION
This function calls:
mredge_combine_ft Combines real and imaginary parts of complex wave field. Needed for FSL FT distortion correction.
mredge_split_ft Splits the FT images into real and imaginary parts. Needed for FSL FT distortion correction
mredge_distortion_correction_ft Correct distortion, applied to the Fourier-transformed wavefield
mredge_distortion_correction_raw Performs distortion correction on raw MR signal data
This function is called by:
mredge Base function for the processing and analysis of MRE data
SOURCE CODE
function mredge_distortion_correction(info, prefs)
% Correct for distortion in the MRE acquisition using FSL or SPM libraries
%
% INPUTS:
%
%   info - an acquisition info structure created with make_acquisition_info
%   prefs - a preference file structure created with mredge_prefs
%
% OUTPUTS:
%
%   none
%
% SEE ALSO:
%
%   mredge_distortion_correction_raw, mredge_distortion_correction_ft
%
% NOTE:
%
%   This requires fieldmaps in the acquisition, specified in the info
%   struct.
%   At present the FT distortion correction is not recommended.
%
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
disp('Distortion correction');
tic
if strcmpi(prefs.dico_method,'ft')
    mredge_split_ft(info, prefs);
    mredge_distortion_correction_ft(info, prefs);
    mredge_combine_ft(info, prefs);
elseif strcmpi(prefs.dico_method,'raw')
    mredge_distortion_correction_raw(info);
else
    disp('MREdge ERROR: Invalid distortion correction method.');
end
toc