Description of mredge_get_placeholder_from_phase
Home > MREdge > file_ops > mredge_get_placeholder_from_phase.m
mredge_get_placeholder_from_phase
PURPOSE
SYNOPSIS
function nifti_placeholder = mredge_get_placeholder_from_phase (info)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
mredge_split_4d Splits a 4D NIfTI into 3D images and passes the list of the 3d image paths. For FSL and SPM applications.
load_untouch_nii_eb Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
This function is called by:
mredge_compat_cisnmo % function mredge_invert(info, prefs);
SUBFUNCTIONS
function PHASE_SUB = set_dirs(info)
SOURCE CODE
function nifti_placeholder = mredge_get_placeholder_from_phase (info)
    PHASE_SUB = set_dirs(info);
    for f = info.driving_frequencies(1)
      for c = 1
        % split to get a 3D file
        file_list_mag = mredge_split_4d(PHASE_SUB, f, c, info);
        nifti_placeholder = load_untouch_nii_eb(file_list_mag{1});
        nifti_placeholder.img = double(nifti_placeholder.img);
        nifti_placeholder.hdr.dime.datatype = 64;
      end
    end
end
function PHASE_SUB = set_dirs(info)
    PHASE_SUB = fullfile(info.path, 'Phase');
end