Description of mredge_split_4d
Home > MREdge > file_ops > mredge_split_4d.m
mredge_split_4d
PURPOSE
Splits a 4D NIfTI into 3D images and passes the list of the 3d image paths. For FSL and SPM applications.
SYNOPSIS
function path_list = mredge_split_4d(path_4d)
DESCRIPTION
 Splits a 4D NIfTI into 3D images and passes the list of the 3d image paths. For FSL and SPM applications.
 INPUTS:
 path_4d - path to the 4D NIfTI
 OUTPUTS:
 file_list - cell of paths to 3d files
 Part of the MREdge software package
 Created 2016 at Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
CROSS-REFERENCE INFORMATION
This function calls:
mredge_remove_nifti_extension Strips file extension from a nifti file, to allow alteration of filenames.
load_untouch_nii_eb Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
This function is called by:
mredge_get_placeholder_from_phase
mredge_aniso_diff % function mredge_aniso_diff(info, prefs);
mredge_gaussian % function mredge_gaussian(info, prefs);
mredge_motion_correction_fsl Applies motion correction using FSL. Requires a Debian installation of FSL 5.0+
mredge_motion_correction_spm Performs motion correction using SPM. Requires SPM 12.
mredge_phase_unwrap Applies phase unwrapping methods.
SOURCE CODE
function path_list = mredge_split_4d(path_4d)
% Splits a 4D NIfTI into 3D images and passes the list of the 3d image paths. For FSL and SPM applications.
%
% INPUTS:
%
% path_4d - path to the 4D NIfTI
%
% OUTPUTS:
%
% file_list - cell of paths to 3d files
%
% Part of the MREdge software package
% Created 2016 at Charite Medical University Berlin
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
path_base = mredge_remove_nifti_extension(path_4d);
vol_4d = load_untouch_nii_eb(path_4d);
path_list = cell(vol_4d.hdr.dime.dim(5),1);
NIF_EXT = getenv('NIFTI_EXTENSION');
for n = 1:size(vol_4d.img, 4)
    vol_3d = vol_4d;
    vol_3d.img = vol_4d.img(:,:,:,n);
    vol_3d.hdr.dime.dim(5) = 1;
    vol_3d.hdr.dime.dim(1) = 3;
    filename_end = char(sprintf("%02d", n));
    path_list{n} = fullfile(path_base, [filename_end, NIF_EXT]);
    save_untouch_nii_eb(vol_3d, path_list{n});
end