Description of mredge_remove_nifti_extension
Home > MREdge > file_ops > mredge_remove_nifti_extension.m
mredge_remove_nifti_extension
PURPOSE
Strips file extension from a nifti file, to allow alteration of filenames.
SYNOPSIS
function path_trunc = mredge_remove_nifti_extension(path)
DESCRIPTION
 Strips file extension from a nifti file, to allow alteration of filenames.
 INPUTS:
 path - a nifti file path, probably from info.ds.subdirs_comps_files
 OUTPUTS:
 truncated pathname
 Part of the MREdge software package
 Created 2016 by Eric Barnhill for Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mredge_split_4d Splits a 4D NIfTI into 3D images and passes the list of the 3d image paths. For FSL and SPM applications.
mredge_distortion_correction_raw Performs distortion correction on raw MR signal data
mredge_motion_correction_fsl Applies motion correction using FSL. Requires a Debian installation of FSL 5.0+
mredge_label_param_map Labels paramater map results and produces statistics for brain anatomical regions.
mredge_masked_median Returns median of masked values for a parameter map
SOURCE CODE
function path_trunc = mredge_remove_nifti_extension(path)
% Strips file extension from a nifti file, to allow alteration of filenames.
%
% INPUTS:
%
% path - a nifti file path, probably from info.ds.subdirs_comps_files
%
% OUTPUTS:
%
% truncated pathname
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
NIF_EXT = getenv('NIFTI_EXTENSION');
trunc_num = numel(NIF_EXT);
path_trunc = path(1:end-trunc_num);