Description of mredge_filename
Home > MREdge > file_ops > mredge_filename.m
mredge_filename
PURPOSE
% function filename = mredge_filename(series, component)
SYNOPSIS
function filename = mredge_filename(series, component, extension, descriptor)
DESCRIPTION
% function filename = mredge_filename(series, component)
 Part of the MREdge software package
 Created 2016 at Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
 USAGE:
 Ensures consistent NIfTI file nomenclature.
 INPUTS:
 series - experimental driving series
 component - component of motion (1, 2, or 3)
 extension - file extension
 descriptor - optional. adds additional string at end. frequently used for temporary files
 OUTPUTS:
 none
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mredge_break_into_frequencies For acquisitions with the all_frequencies_one_series flag, partitions the time series by frequency
mredge_load_magnitude_as_6d % function mredge_laplacian_snr(info, prefs)
mredge_load_phase_as_6d % function mredge_load_phase_as_6d(info, prefs)
mredge_rename_by_frequency For acquisitions where each frequency has its own series number, rename each series to its corresponding frequency.
mredge_reorganize_by_frequency % function mredge_reorganize_by_frequency(subdir, driving_frequencies)
mredge_rezip % function mredge_temporal_ft(info, prefs);
mredge_save_4d_with_spm % function mredge_save_with_spm(path)
mredge_save_5d_as_FT
loop_over_freqs_and_components_4d_nii loop_over_freqs_and_components_4d_nii(info, prefs, fun, IN_DIR_descr, OUT_DIR_descr)
mredge_3d_to_4d_moco % function mredge_3d_to_4d_moco(cell_array, name_4d)
mredge_curl % function mredge_curl(info, prefs);
mredge_denoise_nopar % function mredge_denoise_nopar(info, prefs);
mredge_distortion_correction_ft Correct distortion, applied to the Fourier-transformed wavefield.
mredge_filepath Creates consistent file path given directory, frequency and component
mredge_ft2double % function mredge_ft2double(info,prefs);
mredge_motion_correction_spm Performs motion correction using SPM. Requires SPM 12.
mredge_normalize_phase_prelude % function mredge_normalize_phase(info, prefs);
mredge_remove_divergence Numerical divergence removal of the wave field
mredge_zden % function mredge_denoise(info, prefs);
mredge_amp_wave_snr % function mredge_amp_guided_wave_to_noise(info, prefs);
mredge_amplitudes Creates summed amplitude images
mredge_psf % function mredge_psf(info);
mredge_z_discontinuities % function mredge_denoise(info, prefs);
mredge_z_xy_noise % function mredge_denoise(info, prefs);
SOURCE CODE
%% function filename = mredge_filename(series, component)
%
% Part of the MREdge software package
% Created 2016 at Charite Medical University Berlin
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
% USAGE:
%
% Ensures consistent NIfTI file nomenclature.
%
%
% INPUTS:
%
% series - experimental driving series
% component - component of motion (1, 2, or 3)
% extension - file extension
% descriptor - optional. adds additional string at end. frequently used for temporary files
%
% OUTPUTS:
%
% none
function filename = mredge_filename(series, component, extension, descriptor)
    if nargin < 4
      descriptor = '';
    else
      descriptor = ['_', descriptor];
    end
    if isreal(series)
      freq_str = num2str(series);
    elseif iscell(series)
      freq_str = num2str(cell2mat(series));
    elseif ischar(series)
      freq_str = series;
    else
      display('MREdge ERROR: invalid series field');
      return;
    end
    if isreal(component)
      comp_str = num2str(component);
    elseif iscell(component)
      comp_str = num2str(cell2mat(component));
    elseif ischar(component)
      comp_str = component;
    else
      display('MREdge ERROR: invalid motion component field');
      return;
    end
    filename = [freq_str, '_', comp_str, descriptor, extension];
end