Description of mredge_load_phase_as_6d
Home > MREdge > file_ops > mredge_load_phase_as_6d.m
mredge_load_phase_as_6d
PURPOSE
% function mredge_load_phase_as_6d(info, prefs)
SYNOPSIS
function data_6d = mredge_load_phase_as_6d (info)
DESCRIPTION
% function mredge_load_phase_as_6d(info, prefs)
CROSS-REFERENCE INFORMATION
This function calls:
mredge_filename % function filename = mredge_filename(series, component)
load_untouch_nii_eb Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
This function is called by:
mredge_compat_cisnmo % function mredge_invert(info, prefs);
mredge_invert_compat_cisnmo % function mredge_invert(info, prefs);
SUBFUNCTIONS
function PHASE_SUB = set_dirs(info)
SOURCE CODE
function data_6d = mredge_load_phase_as_6d (info)
%% function mredge_load_phase_as_6d(info, prefs)
%
% Part of the MREdge software package
% Created 2016 at Charite Medical University Berlin
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
% USAGE:
%
% Loads the phase images of the acquisition into a 6D matlab object
%
% INPUTS:
%
% info - an acquisition info structure created by make_acquisition_info
%
% OUTPUTS:
%
% none
%%
    PHASE_SUB = set_dirs(info);
    NIF_EXT = getenv('NIFTI_EXTENSION');
    data_6d = [];
    for f_num = 1:numel(info.driving_frequencies)
        f = info.driving_frequencies(f_num);
        components = [];
        for c = 1:3
            path = fullfile(PHASE_SUB, num2str(f), num2str(c), mredge_filename(f, c, NIF_EXT));
            vol = load_untouch_nii_eb(path);
            img = vol.img;
            components = cat(5, components, img);
        end
        data_6d = cat(6, data_6d, components);
    end
end
function PHASE_SUB = set_dirs(info)
    PHASE_SUB = fullfile(info.path, 'phase');
end