Description of mredge_unzip_if_zip
Home > MREdge > file_ops > mredge_unzip_if_zip.m
mredge_unzip_if_zip
PURPOSE
Unzips nifti if it is zipped. For navigation between SPM, FSL and other packages.
SYNOPSIS
function unzip = mredge_unzip_if_zip(zip)
DESCRIPTION
 Unzips nifti if it is zipped. For navigation between SPM, FSL and other packages.
 INPUTS:
   zip - zipped file path
 OUTPUTS:
   unzip - unzipped file path
 SEE ALSO:
   mredge_zip_if_unzip
 Part of the MREdge software package
 Created 2016 at Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mredge_distortion_correction_ft Correct distortion, applied to the Fourier-transformed wavefield.
mredge_distortion_correction_raw Performs distortion correction on raw MR signal data
mredge_phase_unwrap Applies phase unwrapping methods.
mredge_coreg_param_to_mni Coregisters a parameter map to MNI space using the deformation map from the averaged magnitude.
mredge_label_param_map Labels paramater map results and produces statistics for brain anatomical regions.
mredge_labels_to_mni_space % function mredge_labels_to_mni_space(info, param)
mredge_mni_labels_to_native_space % function mni_labels_to_native_space(info, param)
mredge_mni_to_label_space Transforms MNI space results to SPM label space
mredge_amp_wave_snr % function mredge_amp_guided_wave_to_noise(info, prefs);
SOURCE CODE
function unzip = mredge_unzip_if_zip(zip)
% Unzips nifti if it is zipped. For navigation between SPM, FSL and other packages.
%
% INPUTS:
%
%   zip - zipped file path
%
% OUTPUTS:
%
%   unzip - unzipped file path
%
% SEE ALSO:
%
%   mredge_zip_if_unzip
%
% Part of the MREdge software package
% Created 2016 at Charite Medical University Berlin
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
if strcmp(zip(end-1:end), 'gz') == 1 && exist(zip, 'file')
    unzip = zip(1:end-3);
    gunzip(zip);
    delete(zip);
else
    unzip = zip;
    if exist([zip,'.gz'], 'file')
        gunzip([zip,'.gz']);
        delete([zip,'.gz']);
    end
end