Description of mredge_analysis_path
Home > MREdge > file_ops > mredge_analysis_path.m
mredge_analysis_path
PURPOSE
Generates uniform analysis folder path names
SYNOPSIS
function path = mredge_analysis_path(info, prefs, subdir)
DESCRIPTION
 Generates uniform analysis folder path names
 INPUTS:
   info - MREdge acquisition info structure generated with mredge_acquisition_info
   subdir - name of analysis parameter
 OUTPUTS:
   none
 SEE ALSO:
   mredge_create_analysis_folder
 Part of the MREdge software package
 Created 2016 by Eric Barnhill for Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mredge_combine_ft Combines real and imaginary parts of complex wave field. Needed for FSL FT distortion correction.
mredge_create_analysis_folder If analysis folder does not exist, create it.
mredge_fd_import
mredge_load_FT_as_5d Load Fourier-transformed wavefield into MATLAB.
mredge_load_amplitudes Load amplitude maps into MATLAB.
mredge_load_elastograms Load elastograms into MATLAB.
mredge_organize_acquisition_octave % function mredge_organize_acquisition_octave(info)
mredge_sort_time_steps
mredge_split_ft Splits the FT images into real and imaginary parts. Needed for FSL FT distortion correction.
loop_over_freqs_and_components_4d_nii loop_over_freqs_and_components_4d_nii(info, prefs, fun, IN_DIR_descr, OUT_DIR_descr)
mredge Base function for the processing and analysis of MRE data
mredge_average_magnitude Creates a single, averaged t2 magnitude map from an MRE acquisition, the preferred volume to use for co-registration and segmentation.
mredge_bandpass Applies highpass and lowpass butterworth filters if they are set in prefs
mredge_curl % function mredge_curl(info, prefs);
mredge_denoise Denoise Fourier-transformed wavefield.
mredge_denoise_nopar % function mredge_denoise_nopar(info, prefs);
mredge_distortion_correction_ft Correct distortion, applied to the Fourier-transformed wavefield.
mredge_ft2double % function mredge_ft2double(info,prefs);
mredge_invert_to_end
mredge_load_mask Loads the anatomical mask image and returns as a 3D object
mredge_motion_correction_spm Performs motion correction using SPM. Requires SPM 12.
mredge_phase_unwrap Applies phase unwrapping methods.
mredge_remove_divergence Numerical divergence removal of the wave field
mredge_remove_ipds Removes interslice phase discontinuities.
mredge_save_as_param
mredge_slice_align Dejitters slices using adaptation of Nikolova et al 2001 dejitter algorithm
mredge_temporal_ft Temporally Fourier-transforms the complex wave field.
mredge_zden % function mredge_denoise(info, prefs);
mredge_avg_mag_to_mni Co-registers magnitude image to MNI space. The deformation map is then used to co-register all elasticity maps.
mredge_coreg_param_to_mni Coregisters a parameter map to MNI space using the deformation map from the averaged magnitude.
mredge_coreg_param_to_mni_sliding % function coreg_param_to_mni_sliding(info, param)
mredge_coreg_param_to_mni_springpot % function coreg_param_to_mni_springpot(info, param)
mredge_coreg_param_to_mni_stable % function coreg_param_to_mni_stable(info, param)
mredge_label_param_map Labels paramater map results and produces statistics for brain anatomical regions.
mredge_label_param_map_sliding % function stats = mredge_label_param_map_sliding(info, param)
mredge_label_param_map_springpot % function stats = mredge_label_param_map(info, param)
mredge_label_param_map_stable % function stats = mredge_label_param_map_stable(info, param)
mredge_labels_to_mni_space % function mredge_labels_to_mni_space(info, param)
mredge_mni_labels_to_native_space % function mni_labels_to_native_space(info, param)
mredge_mni_to_label_space Transforms MNI space results to SPM label space
mredge_mni_to_label_space_sliding % function mredge_mni_to_label_space_sliding(info, param)
mredge_mni_to_label_space_springpot % function mredge_mni_to_label_space(info, param)
mredge_mni_to_label_space_stable % function mredge_mni_to_label_space_stable(info, param)
mredge_amp_wave_snr % function mredge_amp_guided_wave_to_noise(info, prefs);
mredge_amplitudes Creates summed amplitude images
mredge_amplitudes_sliding % function mredge_stable_amplitudes(info, prefs);
mredge_cortical_average % function mredge_cortical_average(info, prefs);
mredge_cortical_median % function mredge_cortical_median(info, prefs);
mredge_cortical_median_stable % function mredge_cortical_median(info, prefs);
mredge_displacement_snr % function mredge_laplacian_snr_stable(info, prefs)
mredge_displacement_snr_stable % function mredge_laplacian_snr_stable(info, prefs)
mredge_laplacian_snr % function mredge_laplacian_snr(info, prefs)
mredge_laplacian_snr_stable % function mredge_laplacian_snr_stable(info, prefs)
mredge_masked_median Returns median of masked values for a parameter map
mredge_oss % function mredge_oss(info, prefs);
mredge_psf % function mredge_psf(info);
mredge_rer % function mredge_rer(info, prefs);
mredge_snr Calculates SNR maps and records SNR values in stats folder.
mredge_snr_stable % function mredge_laplacian_snr_stable(info, prefs)
mredge_springpot % function mredge_springpot(info, prefs);
mredge_springpot_stable % function mredge_springpot_stable(info, prefs);
mredge_springpot_stable_weighted % function mredge_springpot_stable_weighted(info, prefs);
mredge_stable_amplitudes % function mredge_stable_amplitudes(info, prefs);
mredge_whole_brain_median % function mredge_whole_brain_median(info, prefs);
mredge_z_discontinuities % function mredge_denoise(info, prefs);
mredge_z_xy_noise % function mredge_denoise(info, prefs);
SOURCE CODE
function path = mredge_analysis_path(info, prefs, subdir)
% Generates uniform analysis folder path names
%
% INPUTS:
%
%   info - MREdge acquisition info structure generated with mredge_acquisition_info
%   subdir - name of analysis parameter
%
% OUTPUTS:
%
%   none
%
% SEE ALSO:
%
%   mredge_create_analysis_folder
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
if numel(prefs.analysis_descriptor) > 0
    prefs.analysis_descriptor = ['_', prefs.analysis_descriptor];
end
if nargin < 3
    path = fullfile(info.path, ['AN_', sprintf('%.3d', prefs.analysis_number), sprintf('%s', prefs.analysis_descriptor)]);
else
    path = fullfile(info.path, ['AN_', sprintf('%.3d', prefs.analysis_number), sprintf('%s', prefs.analysis_descriptor)], subdir);
end