Description of mredge_sort_by_time_series
Home > MREdge > file_ops > mredge_sort_by_time_series.m
mredge_sort_by_time_series
PURPOSE
% function mredge_sort_by_time_series(series_subdir, time_steps)
SYNOPSIS
function mredge_sort_by_time_series(subdir, series, info)
DESCRIPTION
% function mredge_sort_by_time_series(series_subdir, time_steps)
 Part of the MREdge software package
 Created 2016 at Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
 USAGE:
 Organizes DICOM slices into nifti files, guided by acquisition info object, and
 divides into folders by time series.
 INPUTS:
 series_subdir - subdir of DICOM series
 time_steps - time steps in the acquisition. required for 4D conversion
 OUTPUTS:
 none
CROSS-REFERENCE INFORMATION
This function calls:
mredge_timeseries_to_4d % function mredge_timeseries_to_4d(cell_array, name_4d)
This function is called by:
mredge_dicom_to_nii % function mredge_dicom_to_nii(series_num, data_table, subdir, time_steps)
mredge_dicom_to_nii_dcm2niix % function mredge_dicom_to_nii_dcm2niix(series_num, data_table, subdir, time_steps)
mredge_dicom_to_nii_octave % function mredge_dicom_to_nii_octave(series_num, data_table, subdir, time_steps)
mredge_dicom_to_nii_spm % function mredge_dicom_to_nii_som(series_num, data_table, subdir, time_steps)
SOURCE CODE
%% function mredge_sort_by_time_series(series_subdir, time_steps)
%
% Part of the MREdge software package
% Created 2016 at Charite Medical University Berlin
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
% USAGE:
%
% Organizes DICOM slices into nifti files, guided by acquisition info object, and
% divides into folders by time series.
%
% INPUTS:
%
% series_subdir - subdir of DICOM series
% time_steps - time steps in the acquisition. required for 4D conversion
%
% OUTPUTS:
%
% none
%% collect series numbers
function mredge_sort_by_time_series(subdir, series, info)
  series_list = dir(fullfile(subdir, num2str(series), '*.nii'));
  num_time_series = numel(series_list) / info.time_steps;
  for c = 1:num_time_series
      time_series_subdir = fullfile(subdir, num2str(series), num2str(c));
      if ~exist(time_series_subdir, 'dir')
          mkdir(time_series_subdir);
      end
      start_index = (c-1)*info.time_steps + 1;
      end_index = c*info.time_steps;
      for p = start_index:end_index
          movefile(fullfile(subdir, num2str(series), series_list(p).name), fullfile(subdir, num2str(series), num2str(c), series_list(p).name));
      end
      mredge_timeseries_to_4d(subdir, series, c);
  end