Description of mredge_invert_and_stats
Home > MREdge > mredge_invert_and_stats.m
mredge_invert_and_stats
PURPOSE
Performs wave inversion and inversion-related statistical measures
SYNOPSIS
function mredge_invert_and_stats(info, prefs)
DESCRIPTION
 Performs wave inversion and inversion-related statistical measures
 INPUTS:
   info - MREdge acquisition info structure generated with mredge_acquisition_info
   prefs - MREdge preferences structure generated with mredge_prefs
 OUTPUTS:
   none
 NOTE:
 Part of the MREdge software package
 Created 2016 by Eric Barnhill for Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
 run loop across groups for sliding-window multifrequency analysis
CROSS-REFERENCE INFORMATION
This function calls:
mredge_invert Wave inversion of preprocessed MRE data
mredge_brain_analysis Provides co-registration, segmentation and analysis of brain MRE data. Requires SPM12.
mredge_amplitudes Creates summed amplitude images
mredge_masked_median Returns median of masked values for a parameter map
This function is called by:
mredge Base function for the processing and analysis of MRE data
SUBFUNCTIONS
function invert_and_stats(info, prefs, freq_indices)
SOURCE CODE
function mredge_invert_and_stats(info, prefs)
% Performs wave inversion and inversion-related statistical measures
%
% INPUTS:
%
%   info - MREdge acquisition info structure generated with mredge_acquisition_info
%   prefs - MREdge preferences structure generated with mredge_prefs
%
% OUTPUTS:
%
%   none
%
% NOTE:
%
%
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
% run loop across groups for sliding-window multifrequency analysis
if prefs.sliding_windows == 1
    [~, freq_indices] = sort(info.driving_frequencies, 'ascend');
    for n = 1:nf-2
        sliding_group_indices = [freq_indices(n), freq_indices(n+1), freq_indices(n+2)];
        invert_and_stats(info,prefs,sliding_group_indices);
    end
else
    invert_and_stats(info,prefs);
end
end
function invert_and_stats(info, prefs, freq_indices)
    % sort out freq indices
    if isempty(freq_indices)
        if isempty(prefs.freq_indices)
            freq_indices = 1:numel(prefs.driving_frequencies);
        else
            freq_indices = prefs.freq_indices;
        end
    end
    % now process
    mredge_amplitudes(info, prefs, freq_indices);
    if ~strcmp(prefs.inversion_strategy, 'none')
        mredge_invert(info, prefs, freq_indices);
        mredge_masked_median(info, prefs, freq_indices);
        if prefs.brain_analysis
            mredge_brain_analysis(info, prefs, freq_indices);
        end
    end
end