Description of mredge_normalize_phase_prelude
Home > MREdge > mredge_normalize_phase_prelude.m
mredge_normalize_phase_prelude
PURPOSE
% function mredge_normalize_phase(info, prefs);
SYNOPSIS
function mredge_normalize_phase_prelude(info, prefs)
DESCRIPTION
% function mredge_normalize_phase(info, prefs);
 Part of the MREdge software package
 Created 2016 by Eric Barnhill for Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
 USAGE:
   Normalizes the phase of the data to [0, 2pi) .
 INPUTS:
   info - MREdge acquisition info structure generated with mredge_acquisition_info
   prefs - MREdge preferences structure generated with mredge_prefs
 OUTPUTS:
   none
CROSS-REFERENCE INFORMATION
This function calls:
mredge_filename % function filename = mredge_filename(series, component)
load_untouch_nii_eb Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
normalizeImage
mredge_phase2double Converts values in phase NIfTI objects to double type, to avoid type conflicts.
This function is called by:
SUBFUNCTIONS
function [PHASE_SUB] = set_dirs(info)
SOURCE CODE
%% function mredge_normalize_phase(info, prefs);
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
%
% USAGE:
%
%   Normalizes the phase of the data to [0, 2pi) .
%
% INPUTS:
%
%   info - MREdge acquisition info structure generated with mredge_acquisition_info
%   prefs - MREdge preferences structure generated with mredge_prefs
%
% OUTPUTS:
%
%   none
function mredge_normalize_phase_prelude(info, prefs)
    [PHASE_SUB] =set_dirs(info);
    NIF_EXT = getenv('NIFTI_EXTENSION');
        for f = info.driving_frequencies
            for c = 1:3
                path = fullfile(PHASE_SUB, num2str(f), num2str(c), mredge_filename(f, c, NIF_EXT));
                phase_vol = load_untouch_nii_eb(path);
                    if ~isempty(prefs.phase_unwrapping_settings.phase_range)
                        range_array = prefs.phase_unwrapping_settings.phase_range;
                        range = range_array(2) - range_array(1);
                        phase_vol.img = ( (phase_vol.img - range_array(1)) / range ) * pi;
                    else
                        phase_vol.img = normalizeImage(phase_vol.img) *pi;
                    end
                save_untouch_nii(phase_vol, path);
            end
        end
        mredge_phase2double(info); % because FSL automatically converts to single;
end
function [PHASE_SUB] = set_dirs(info)
    PHASE_SUB = fullfile(info.path, 'Phase');
end