Description of mredge_denoise
Home > MREdge > mredge_denoise.m
mredge_denoise
PURPOSE
Denoise Fourier-transformed wavefield.
SYNOPSIS
function mredge_denoise(info, prefs)
DESCRIPTION
 Denoise Fourier-transformed wavefield.
 USAGE:
   mredge_denoise(info, prefs)
 INPUTS:
   info - MREdge acquisition info structure generated with mredge_acquisition_info
   prefs - MREdge preferences structure generated with mredge_prefs
 OUTPUTS:
   none
 NOTE:
   If you use these denoising algorithms please cite:
   Barnhill et al. Nonlinear Multiscale Regularization in MR Elastography
   Med Image Anal. 2017 Jan;35:133-145. doi: 10.1016/j.media.2016.05.012
 Part of the MREdge software package
 Created 2016 by Eric Barnhill for Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
CROSS-REFERENCE INFORMATION
This function calls:
mredge_analysis_path Generates uniform analysis folder path names
load_untouch_nii_eb Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
dtdenoise_3d_mad_ogs_undec_log 3D Dualtree complex denoising
dtdenoise_xy_pca_mad_u
dtdenoise_z_mad_u
dtdenoise_2d_undec 2D Dualtree complex denoising
dtdenoise_z_mad_u
mredge_load_mask Loads the anatomical mask image and returns as a 3D object
This function is called by:
mredge Base function for the processing and analysis of MRE data
mredge_ft_to_end % function [outputs] = mredge_ft_to_end(info, prefs);
mredge_octave % function [outputs] = mredge_octave(info, prefs);
SOURCE CODE
function mredge_denoise(info, prefs)
% Denoise Fourier-transformed wavefield.
%
% USAGE:
%
%   mredge_denoise(info, prefs)
%
% INPUTS:
%
%   info - MREdge acquisition info structure generated with mredge_acquisition_info
%   prefs - MREdge preferences structure generated with mredge_prefs
%
% OUTPUTS:
%
%   none
%
% NOTE:
%
%   If you use these denoising algorithms please cite:
%   Barnhill et al. Nonlinear Multiscale Regularization in MR Elastography
%   Med Image Anal. 2017 Jan;35:133-145. doi: 10.1016/j.media.2016.05.012
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
tic
disp('Denoising...');
mask = mredge_load_mask(info, prefs);
parfor s = 1:numel(info.ds.subdirs_comps_files)
  subdir = info.ds.subdirs_comps_files(s); %#ok<PFBNS>
  wavefield_path = cell2str(fullfile(mredge_analysis_path(info, prefs, 'FT'), subdir));
  wavefield_vol = load_untouch_nii_eb(wavefield_path);
  wavefield_img = wavefield_vol.img;
  resid_vol = wavefield_vol;
  fprintf(fileID, '%s \n', cell2str(subdir));
  if strcmpi(prefs.denoise_strategy, 'z-xy') == 1
      wavefield_img = dtdenoise_z_mad_u(wavefield_img, prefs.denoise_settings.z_thresh, prefs.denoise_settings.z_level, 1);
      wavefield_img = dtdenoise_xy_pca_mad_u(wavefield_img, prefs.denoise_settings.xy_thresh, prefs.denoise_settings.xy_level, 1, mask);
  elseif strcmpi(prefs.denoise_strategy, '3d_soft_visu') == 1
      wavefield_img = dtdenoise_3d_undec(wavefield_img, prefs.denoise_settings.full3d_level, mask, prefs.denoise_settings.threshold_gain);
   elseif strcmpi(prefs.denoise_strategy, '3d_nng_visu') == 1
      wavefield_img = dtdenoise_3d_nng(wavefield_img, prefs.denoise_settings.full3d_level, mask, prefs.denoise_settings.threshold_gain);
  elseif strcmpi(prefs.denoise_strategy, '3d_ogs') == 1
      wavefield_img = dtdenoise_3d_mad_ogs_undec_log(wavefield_img, prefs.denoise_settings.full3d_thresh, prefs.denoise_settings.full3d_level, mask, fileID, prefs.base1, prefs.base2);
  elseif strcmpi(prefs.denoise_strategy, '2d_soft_visu')
      wavefield_img = dtdenoise_2d_undec(wavefield_img,  prefs.denoise_settings.xy_level, mask);
      wavefield_img(isnan(wavefield_img)) = 0;
  end
  wavefield_vol.img = wavefield_img;
  resid_vol.img = resid_vol.img - wavefield_img;
  save_untouch_nii(wavefield_vol, wavefield_path);
  resid_dir = fullfile(mredge_analysis_path(info, prefs, 'denoise_resid'));
  resid_path = cell2str(fullfile(resid_dir, subdir));
  save_untouch_nii_eb(resid_vol, resid_path);
end
toc