Description of mredge_invert_mdev
Home > MREdge > mredge_invert_mdev.m
mredge_invert_mdev
PURPOSE
% function mredge_invert_mdev(info, prefs, freq_indices);
SYNOPSIS
function mredge_invert_mdev(info, prefs, freq_indices)
DESCRIPTION
% function mredge_invert_mdev(info, prefs, freq_indices);
 Part of the MREdge software package
 Created 2016 by Eric Barnhill for Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
 USAGE:
   create an elastogram of param using the all approach
   If you use this method cite
   Braun, Jürgen, Jing Guo, Ralf Lützkendorf, Jörg Stadler, Sebastian
   Papazoglou, Sebastian Hirsch, Ingolf Sack, and Johannes Bernarding.
   "High-resolution mechanical imaging of the human brain by
   three-dimensional multifrequency magnetic resonance elastography at
   7T." Neuroimage 90 (2014): 308-314.
   and preferably also
   Papazoglou, Sebastian, Sebastian Hirsch, Jürgen Braun, and Ingolf
   Sack. "Multifrequency inversion in magnetic resonance elastography."
   Physics in medicine and biology 57, no. 8 (2012): 2329.
 INPUTS:
   info - MREdge acquisition info structure generated with mredge_acquisition_info
   prefs - MREdge preferences structure generated with mredge_prefs
   param - name of all-compatible parameter: 'absg', 'phi', 'c' or 'a'
 OUTPUTS:
   none
CROSS-REFERENCE INFORMATION
This function calls:
mredge_analysis_path % function mredge_analysis_path(info, subdir);
mredge_filename % function filename = mredge_filename(series, component)
mredge_freq_indices_to_filename
mredge_get_ft_dirs % function mredge_get_ft_dirs(info, prefs);
load_untouch_nii_eb Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
This function is called by:
mredge_invert % function mredge_invert(info, prefs);
SUBFUNCTIONS
function [FT_DIRS, PARAM_SUB] = set_dirs(info, prefs, param)
SOURCE CODE
%% function mredge_invert_mdev(info, prefs, freq_indices);
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
%
% USAGE:
%
%   create an elastogram of param using the all approach
%
%   If you use this method cite
%
%   Braun, Jürgen, Jing Guo, Ralf Lützkendorf, Jörg Stadler, Sebastian
%   Papazoglou, Sebastian Hirsch, Ingolf Sack, and Johannes Bernarding.
%   "High-resolution mechanical imaging of the human brain by
%   three-dimensional multifrequency magnetic resonance elastography at
%   7T." Neuroimage 90 (2014): 308-314.
%
%   and preferably also
%
%   Papazoglou, Sebastian, Sebastian Hirsch, Jürgen Braun, and Ingolf
%   Sack. "Multifrequency inversion in magnetic resonance elastography."
%   Physics in medicine and biology 57, no. 8 (2012): 2329.
%
% INPUTS:
%
%   info - MREdge acquisition info structure generated with mredge_acquisition_info
%   prefs - MREdge preferences structure generated with mredge_prefs
%   param - name of all-compatible parameter: 'absg', 'phi', 'c' or 'a'
%
% OUTPUTS:
%
%   none
function mredge_invert_mdev(info, prefs, freq_indices)
    frequencies = info.driving_frequencies;
    if nargin < 3 || isempty(freq_indices)
        freq_indices = 1:numel(frequencies);
    end
    [FT_DIRS, PARAM_SUB] =set_dirs(info, prefs, 'Abs_G');
    NIF_EXT = getenv('NIFTI_EXTENSION');
    if numel(unique(info.voxel_spacing)) == 1
        ndims = 4;
        iso = 1;
    else
        ndims = 2;
        iso = 0;
    end
    all_u = [];
    for f_ind = freq_indices
        f = info.driving_frequencies(f_ind);
        freq_u = [];
        for c = 1:3
            for d = 1:numel(FT_DIRS)
                wavefield_path = fullfile(FT_DIRS{d}, num2str(f), num2str(c), mredge_filename(f, c, NIF_EXT));
                wavefield_vol = load_untouch_nii_eb(wavefield_path);
                wavefield_img = double(wavefield_vol.img);
                freq_u = cat(4, freq_u, wavefield_img);
            end
        end
        all_u = cat(5, all_u, freq_u);
    end
    if prefs.inversion_settings.bootstrap
        [x0, x1] = bootstrap_helmholtz(double(all_u), info.driving_frequencies, info.voxel_spacing);
        mean_freq = mean(info.driving_frequencies);
        absg = x0 + x1*mean_freq;
    else
        if strcmpi(prefs.gradient_strategy, 'fd')
            absg = helmholtz_inversion(all_u, info.driving_frequencies(freq_indices), info.voxel_spacing, ...
            prefs.inversion_settings.mdev_laplacian_dims, 4, iso);
        elseif strcmpi(prefs.gradient_strategy, 'lsq')
            absg = helm_inv_rg(all_u, info.driving_frequencies(freq_indices), info.voxel_spacing);
        end
    end
    param_all = wavefield_vol;
    param_all.img = absg;
    %param_all = update_nifti_dims(param_all);
    param_all.hdr.dime.datatype = 64;
    param_all_dir = fullfile(PARAM_SUB);
    if ~exist(param_all_dir, 'dir')
       mkdir(param_all_dir);
    end
    param_path = fullfile(param_all_dir, mredge_freq_indices_to_filename(info, prefs));
    save_untouch_nii(param_all, param_path);
end
function [FT_DIRS, PARAM_SUB] = set_dirs(info, prefs, param)
    FT_DIRS = mredge_get_ft_dirs(info, prefs);
    PARAM_SUB = mredge_analysis_path(info, prefs, param);
end