Description of mredge_invert_compat_cisnmo
Home > MREdge > mredge_invert_compat_cisnmo.m
mredge_invert_compat_cisnmo
PURPOSE
% function mredge_invert(info, prefs);
SYNOPSIS
function mredge_compat_cisnmo(info, prefs)
DESCRIPTION
% function mredge_invert(info, prefs);
 Part of the MREdge software package
 Created 2016 by Eric Barnhill for Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
 USAGE:
   to come
 INPUTS:
   info - MREdge acquisition info structure generated with mredge_acquisition_info
   prefs - MREdge preferences structure generated with mredge_prefs
 OUTPUTS:
   none
CROSS-REFERENCE INFORMATION
This function calls:
evalmmre_cisnmo function [ABSG,PHI,ABSG_orig,PHI_orig,AMP,varmapX, varmapY, offsetX, offsetY] = evalmmre(W_wrap,freqs)
mredge_load_phase_as_6d % function mredge_load_phase_as_6d(info, prefs)
mredge_save_as_param
This function is called by:
mredge_ft_to_end % function [outputs] = mredge_ft_to_end(info, prefs);
mredge_ft_to_end_nopar % function [outputs] = mredge_ft_to_end_nopar(info, prefs);
SOURCE CODE
%% function mredge_invert(info, prefs);
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
%
% USAGE:
%
%   to come
%
% INPUTS:
%
%   info - MREdge acquisition info structure generated with mredge_acquisition_info
%   prefs - MREdge preferences structure generated with mredge_prefs
%
% OUTPUTS:
%
%   none
function mredge_compat_cisnmo(info, prefs)
    phase_data = mredge_load_phase_as_6d(info, prefs);
    [ABSG,PHI,ABSG_orig,PHI_orig,AMP] = evalmmre_cisnmo(phase_data,info.driving_frequencies,info.pixel_spacing);
    for param_name = {'ABSG', 'ABSG_orig', 'PHI', 'PHI_orig', 'AMP'};
        mredge_save_as_param(info, prefs, param_name, eval(param_name));
    end
end