Description of mredge_denoise_nopar
Home > MREdge > mredge_denoise_nopar.m
mredge_denoise_nopar
PURPOSE
% function mredge_denoise_nopar(info, prefs);
SYNOPSIS
function mredge_denoise_nopar(info, prefs)
DESCRIPTION
% function mredge_denoise_nopar(info, prefs);
 Part of the MREdge software package
 Created 2016 by Eric Barnhill for Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
 USAGE:
   Denoise the complex wave field, without parallel processing.
    Good for step debugging.
 INPUTS:
   info - MREdge acquisition info structure generated with mredge_acquisition_info
   prefs - MREdge preferences structure generated with mredge_prefs
 OUTPUTS:
   none
CROSS-REFERENCE INFORMATION
This function calls:
mredge_analysis_path Generates uniform analysis folder path names
mredge_filename % function filename = mredge_filename(series, component)
load_untouch_nii_eb Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
dtdenoise_xy_pca_mad
dtdenoise_xy_pca_mad_amp
dtdenoise_z_auto_noise_est
mredge_convert_norm_thresh_to_wpm % function mredge_convert_norm_thresh_to_wpm(thresh, voxel_spacing, h, w);
mredge_denoise_3d % function y = mredge_denoise_3d(x, info, prefs)
This function is called by:
mredge_ft_to_end_nopar % function [outputs] = mredge_ft_to_end_nopar(info, prefs);
SUBFUNCTIONS
function [FT_DIRS, RESID_DIRS] = set_dirs(info, prefs)
SOURCE CODE
%% function mredge_denoise_nopar(info, prefs);
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
%
% USAGE:
%
%   Denoise the complex wave field, without parallel processing.
%    Good for step debugging.
%
% INPUTS:
%
%   info - MREdge acquisition info structure generated with mredge_acquisition_info
%   prefs - MREdge preferences structure generated with mredge_prefs
%
% OUTPUTS:
%
%   none
function mredge_denoise_nopar(info, prefs)
    [FT_DIRS, RESID_DIRS] = set_dirs(info, prefs);
    NIF_EXT = '.nii.gz';
    for n = 1:numel(RESID_DIRS)
        if ~exist(RESID_DIRS{n}, 'dir')
            mkdir(RESID_DIRS{n});
        end
    end
    for d = 1:numel(FT_DIRS);
        for f_num = 1:numel(info.driving_frequencies)
            f = info.driving_frequencies(f_num); %#ok<PFBNS>
            display([num2str(f), ' Hz']);
            for c = 1:3
                display(num2str(c));
                wavefield_path = fullfile(FT_DIRS{d}, num2str(f), num2str(c), mredge_filename(f, c, NIF_EXT)); %#ok<PFBNS>
                wavefield_vol = load_untouch_nii_eb(wavefield_path);
                wavefield_img = wavefield_vol.img;
                resid_vol = wavefield_vol;
                if strcmp(prefs.denoise_strategy, 'z_xy') == 1 %#ok<PFBNS>
                    wavefield_img = dtdenoise_z_auto_noise_est(wavefield_img, prefs.denoise_settings.z_level, prefs.denoise_settings.z_thresh_factor);
                    wavefield_img = dtdenoise_xy_pca_mad(wavefield_img, prefs.denoise_settings.xy_thresh_factor, prefs.denoise_settings.xy_num_spins);
                elseif strcmp(prefs.denoise_strategy, 'z_xy_ampguided') == 1 %#ok<PFBNS>
                    amp = abs(wavefield_img);
                    wavefield_img = dtdenoise_z_auto_noise_est(wavefield_img, prefs.denoise_settings.z_level, prefs.denoise_settings.z_thresh_factor);
                    wavefield_img = dtdenoise_xy_pca_mad_amp(wavefield_img, amp, prefs.denoise_settings.xy_thresh_factor, prefs.denoise_settings.xy_num_spins);
                elseif strcmp(prefs.denoise_strategy, 'lowpass') == 1
                    if prefs.lowpass_settings.dimensions == 2
                        if strcmp(prefs.lowpass_settings.cutoff_unit, 'norm') == 1
                            wpm = mredge_convert_norm_thresh_to_wpm(prefs.lowpass_settings.cutoff, info.voxel_spacing(1), size(wavefield_img, 1), size(wavefield_img, 2));
                        elseif strcmp(prefs.lowpass_settings.cutoff_unit, 'wpm') == 1
                            disp('wpm');
                            wpm = prefs.lowpass_settings.cutoff;
                        else
                            display('MREdge ERROR: Lowpass denoise settings not compatible.');
                        end
                        for z=1:size(wavefield_img,3)
                           wavefield_img(:,:,z) = uh_filtspatio2d(wavefield_img(:,:,z),[info.voxel_spacing(1); info.voxel_spacing(2)],prefs.lowpass_settings.cutoff,1,0,5, 'bwlow', 0);
                        end
                    end
                elseif strcmp(prefs.denoise_strategy, '3d') == 1
                    wavefield_img = mredge_denoise_3d(wavefield_img);
                end
                wavefield_vol.img = wavefield_img;
                resid_vol.img = resid_vol.img - wavefield_img;
                save_untouch_nii(wavefield_vol, wavefield_path);
                resid_dir = fullfile(RESID_DIRS{d}, num2str(f), num2str(c));  %#ok<PFBNS>
                if ~exist(resid_dir, 'dir')
                    mkdir(resid_dir);
                end
                resid_path = fullfile(resid_dir, mredge_filename(f, c, NIF_EXT));
                save_untouch_nii(resid_vol, resid_path);
            end
        end
    end
end
function [FT_DIRS, RESID_DIRS] = set_dirs(info, prefs)
    if strcmp(prefs.phase_unwrap, 'gradient') == 1;
        FT_X = mredge_analysis_path(info,prefs,'FT_X');
        FT_Y = mredge_analysis_path(info,prefs,'FT_Y');
        FT_DIRS = cell(2,1);
        FT_DIRS{1} = FT_X;
        FT_DIRS{2} = FT_Y;
        RESID_X = mredge_analysis_path(info,prefs,'DENOISE_RESID_X');
        RESID_Y = mredge_analysis_path(info,prefs,'DENOISE_RESID_Y');
        RESID_DIRS = cell(2,1);
        RESID_DIRS{1} = RESID_X;
        RESID_DIRS{2} = RESID_Y;
    else
        FT_SUB = mredge_analysis_path(info,prefs,'FT');
        FT_DIRS = cell(1,1);
        FT_DIRS{1} = FT_SUB;
        RESID_SUB = mredge_analysis_path(info,prefs,'DENOISE_RESID');
        RESID_DIRS = cell(1,1);
        RESID_DIRS{1} = RESID_SUB;
    end
end