Description of mredge_octave
Home > MREdge > mredge_octave.m
mredge_octave
PURPOSE
% function [outputs] = mredge_octave(info, prefs);
SYNOPSIS
function [matlab_outputs] = mredge_octave(info, prefs)
DESCRIPTION
% function [outputs] = mredge_octave(info, prefs);
 Part of the MREdge software package
 Created 2016 by Eric Barnhill for Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
 USAGE:
   calls inversion pipeline specified in prefs on data set specified in info
   may contain tweaks for Octave compatibility
 INPUTS:
   info - MREdge acquisition info structure generated with mredge_acquisition_info
   prefs - MREdge preferences structure generated with mredge_prefs
 OUTPUTS:
   returns a structure containing outputs as specified by prefs
CROSS-REFERENCE INFORMATION
This function calls:
mredge_clean_acquisition_folder Cleans all processing files from local acquisition folder, leaving only DICOMs.
mredge_organize_acquisition_octave % function mredge_organize_acquisition_octave(info)
mredge_aniso_diff % function mredge_aniso_diff(info, prefs);
mredge_average_magnitude Creates a single, averaged t2 magnitude map from an MRE acquisition, the preferred volume to use for co-registration and segmentation.
mredge_curl % function mredge_curl(info, prefs);
mredge_denoise Denoise Fourier-transformed wavefield.
mredge_distortion_correction Correct for distortion in the MRE acquisition using FSL or SPM libraries
mredge_gaussian % function mredge_gaussian(info, prefs);
mredge_invert Wave inversion of preprocessed MRE data
mredge_mag2double Converts values in magnitude NIfTI objects to double type, to avoid type conflicts.
mredge_motion_correction Performs motion correction on raw MRE acquisitions, using FSL or SPM.
mredge_phase_unwrap Applies phase unwrapping methods.
mredge_temporal_ft Temporally Fourier-transforms the complex wave field.
mredge_brain_analysis Provides co-registration, segmentation and analysis of brain MRE data. Requires SPM12.
mredge_amp_wave_snr % function mredge_amp_guided_wave_to_noise(info, prefs);
mredge_amplitudes Creates summed amplitude images
mredge_cortical_median % function mredge_cortical_median(info, prefs);
mredge_cortical_median_stable % function mredge_cortical_median(info, prefs);
mredge_oss % function mredge_oss(info, prefs);
mredge_psf % function mredge_psf(info);
mredge_rer % function mredge_rer(info, prefs);
mredge_springpot % function mredge_springpot(info, prefs);
mredge_springpot_stable % function mredge_springpot_stable(info, prefs);
mredge_springpot_stable_weighted % function mredge_springpot_stable_weighted(info, prefs);
mredge_stable_amplitudes % function mredge_stable_amplitudes(info, prefs);
mredge_z_xy_noise % function mredge_denoise(info, prefs);
This function is called by:
SUBFUNCTIONS
function outputs = initialize_matlab_outputs
SOURCE CODE
%% function [outputs] = mredge_octave(info, prefs);
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
%
% USAGE:
%
%   calls inversion pipeline specified in prefs on data set specified in info
%   may contain tweaks for Octave compatibility
%
% INPUTS:
%
%   info - MREdge acquisition info structure generated with mredge_acquisition_info
%   prefs - MREdge preferences structure generated with mredge_prefs
%
% OUTPUTS:
%
%   returns a structure containing outputs as specified by prefs
function [matlab_outputs] = mredge_octave(info, prefs)
    time_all = tic;
    matlab_outputs = initialize_matlab_outputs;
    display('Organizing files')
    tic
    % OSS SNR ROUTINES
    if prefs.outputs.snr == 1
        mredge_clean_acquisition_folder(info);
        mredge_organize_acquisition_octave(info, prefs);
        mredge_mag2double(info);
        mredge_average_magnitude(info, prefs);
        mredge_amp_wave_snr(info, prefs);
        mredge_oss(info, prefs);
    end
    % INVERSION
    mredge_clean_acquisition_folder(info);
    mredge_organize_acquisition_octave(info, prefs);
    mredge_mag2double(info);
    toc
    if prefs.distortion_correction == 1
        display('Distortion correction');
        tic
        mredge_distortion_correction(info, prefs);
        toc
    end
    if prefs.motion_correction == 1
        display('Motion correction');
        tic
        mredge_motion_correction(info, prefs);
        toc
    end
    %psf stats
    mredge_psf(info, prefs);
    if prefs.aniso_diff == 1
        display('Anisotropic Diffusion')
        tic
        mredge_aniso_diff(info, prefs);
        toc
    end
    if prefs.gaussian == 1
        display('Gaussian Smoothing')
        tic
        mredge_gaussian(info, prefs);
        toc
    end
    if strcmp(prefs.phase_unwrap, 'none') == 0
        display('Phase Unwrapping')
        tic
        mredge_phase_unwrap(info, prefs);
        toc
    end
    % if no Temporal FT, some new routines need to be written
    if prefs.temporal_ft == 1
        display('Temporal FT');
        tic
        mredge_temporal_ft(info, prefs);
        toc
    else
        display('MREdge ERROR: Not implemented without FT yet.');
        return
        %mredge_copy_no_ft(info);
    end
    % z stats
    % run once while noised, once after denoising
    mredge_z_xy_noise(info, prefs);
    if strcmp(prefs.denoise_strategy, 'none') == 0
        display('Denoising');
        tic
        mredge_denoise(info, prefs);
        toc
    end
    if strcmp(prefs.curl_strategy, 'none') == 0
        display('Curl Decomposition');
        tic
        mredge_curl(info, prefs);
        toc
    end
    mredge_amplitudes(info, prefs);
    mredge_stable_amplitudes(info, prefs);
    if strcmp(prefs.inversion_strategy, 'none') == 0
        display('Wave Inversion');
        tic
        mredge_invert(info, prefs);
        toc
    end
    mredge_rer(info, prefs);
    mredge_springpot(info, prefs);
    mredge_springpot_stable(info,prefs);
    mredge_springpot_stable_weighted(info, prefs);
    mredge_cortical_median(info, prefs);
    mredge_cortical_median_stable(info, prefs);
    if prefs.brain_analysis == 1
        mredge_brain_analysis(info, prefs);
    end
    % set outputs
    %{
    if prefs.outputs.matlab.absg == 1
        outputs.mag = mredge_load_absg;
    end
    if prefs.outputs.matlab.phi == 1
        outputs.phi = mredge_load_phi;
    end
    if prefs.outputs.matlab.c == 1
        outputs.c = mredge_load_c;
    end
    if prefs.outputs.matlab.a == 1
        outputs.a = mredge_load_a;
    end
    if prefs.outputs.matlab.wavefield == 1
        outputs.wavefield = mredge_load_wavefield;
    end
    if prefs.outputs.matlab.snr == 1
        outputs.snr = mredge_load_snr;
    end
    %}
    toc(time_all)
end
function outputs = initialize_matlab_outputs
  outputs.mag = [];
  outputs.phi = [];
  outputs.c = [];
  outputs.a = [];
  outputs.wavefield =[];
  outputs.snr = [];
end