Description of mredge_invert_sliding
Home > MREdge > mredge_invert_sliding.m
mredge_invert_sliding
PURPOSE
% function mredge_invert_sliding(info, prefs,invert);
SYNOPSIS
function [stable_filenames, stable_frequencies] = mredge_invert_sliding(info, prefs, invert)
DESCRIPTION
% function mredge_invert_sliding(info, prefs,invert);
 Part of the MREdge software package
 Created 2016 by Eric Barnhill for Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
CROSS-REFERENCE INFORMATION
This function calls:
mredge_invert_param_mdev % function mredge_invert_param_all(info, prefs, param, freq_indices);
mredge_invert_sfwi % function mredge_invert_sfwi(info, prefs);
This function is called by:
mredge_invert % function mredge_invert(info, prefs);
mredge_coreg_param_to_mni_sliding % function coreg_param_to_mni_sliding(info, param)
mredge_label_param_map_sliding % function stats = mredge_label_param_map_sliding(info, param)
mredge_mni_to_label_space_sliding % function mredge_mni_to_label_space_sliding(info, param)
mredge_laplacian_snr % function mredge_laplacian_snr(info, prefs)
mredge_masked_median mredge_masked_median(info, prefs);
SOURCE CODE
%% function mredge_invert_sliding(info, prefs,invert);
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
%
function [stable_filenames, stable_frequencies] = mredge_invert_sliding(info, prefs, invert)
    NIF_EXT = getenv('NIFTI_EXTENSION');
    if nargin < 2
        invert = 0;
    end
    df = info.driving_frequencies;
    nf = numel(df);
    stable_filenames = cell(nf-2, 1);
    stable_frequencies = zeros(nf-2, 1);
    [freqs_sorted, freq_indices] = sort(info.driving_frequencies, 'ascend');
    for n = 1:nf-2
        stable_group = [freqs_sorted(n), freqs_sorted(n+1), freqs_sorted(n+2)];
        stable_group_indices = [freq_indices(n), freq_indices(n+1), freq_indices(n+2)];
        if invert == 1
            if strcmpi(prefs.inversion_strategy,'MDEV') == 1
                mredge_invert_param_mdev(info, prefs, 'Abs_G', stable_group_indices);
            elseif strcmpi(prefs.inversion_strategy,'SFWI') == 1
                mredge_invert_sfwi(info, prefs, stable_group_indices);
            end
        end
        stable_filenames{n} = [num2str(stable_group(1)),'_',num2str(stable_group(2)),'_',num2str(stable_group(3)), NIF_EXT];
        stable_frequencies(n) = mean(stable_group);
    end
end