Description of mredge_ri2pm
Home > MREdge > mredge_ri2pm.m
mredge_ri2pm
PURPOSE
Converts real and imagianry data to phase and magnitude
SYNOPSIS
function mredge_ri2pm(info)
DESCRIPTION
 Converts real and imagianry data to phase and magnitude
 INPUTS:
 dir - location of the time series
 OUTPUTS:
 none
 SEE ALSO:
   mredge_pm2ri
 Part of the MREdge software package
 Created 2016 at Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
CROSS-REFERENCE INFORMATION
This function calls:
load_untouch_nii_eb Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
This function is called by:
mredge_aniso_diff % function mredge_aniso_diff(info, prefs);
mredge_denoise_raw Denoises raw complex data prior to phase unwrapping
mredge_distortion_correction_raw Performs distortion correction on raw MR signal data
mredge_gaussian % function mredge_gaussian(info, prefs);
mredge_motion_correction_fsl Applies motion correction using FSL. Requires a Debian installation of FSL 5.0+
mredge_motion_correction_spm Performs motion correction using SPM. Requires SPM 12.
mredge_raw_denoise
SOURCE CODE
function mredge_ri2pm(info)
% Converts real and imagianry data to phase and magnitude
%
% INPUTS:
%
% dir - location of the time series
%
% OUTPUTS:
%
% none
%
% SEE ALSO:
%
%   mredge_pm2ri
%
% Part of the MREdge software package
% Created 2016 at Charite Medical University Berlin
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
    for subdir = info.ds.subdirs_comps_files
        % load re and im
        re = load_untouch_nii_eb(cell2str(fullfile(info.ds.list(info.ds.enum.real), subdir)));
        im = load_untouch_nii_eb(cell2str(fullfile(info.ds.list(info.ds.enum.imaginary), subdir)));
        % create placeholder p and m
        p = re;
        m = im;
        % calculate
        cplx = re.img + 1i*im.img;
        p.img = angle(cplx);
        m.img = abs(cplx);
        % write p and m
        save_untouch_nii_eb(p, cell2str(fullfile(info.ds.list(info.ds.enum.phase), subdir)));
        save_untouch_nii_eb(m, cell2str(fullfile(info.ds.list(info.ds.enum.magnitude), subdir)));
    end
end