Description of mredge_load_mask
Home > MREdge > mredge_load_mask.m
mredge_load_mask
PURPOSE
Loads the anatomical mask image and returns as a 3D object
SYNOPSIS
function mask = mredge_load_mask(info, prefs)
DESCRIPTION
 Loads the anatomical mask image and returns as a 3D object
 INPUTS:
 info - an acquisition info structure created with make_acquisition_info
 prefs - preferences file created with mredge_prefs
 OUTPUTS:
 none
 Part of the MREdge software package
 Created 2016 by Eric Barnhill for Charite Medical University Berlin
 Private usage only. Distribution only by permission of Elastography working
 group.
CROSS-REFERENCE INFORMATION
This function calls:
mredge_analysis_path Generates uniform analysis folder path names
load_untouch_nii_eb Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
This function is called by:
mredge_bandpass Applies highpass and lowpass butterworth filters if they are set in prefs
mredge_denoise Denoise Fourier-transformed wavefield.
mredge_phase_unwrap Applies phase unwrapping methods.
mredge_remove_ipds Removes interslice phase discontinuities.
mredge_zden % function mredge_denoise(info, prefs);
mredge_amp_wave_snr % function mredge_amp_guided_wave_to_noise(info, prefs);
mredge_cortical_average % function mredge_cortical_average(info, prefs);
mredge_cortical_median % function mredge_cortical_median(info, prefs);
mredge_cortical_median_stable % function mredge_cortical_median(info, prefs);
mredge_displacement_snr % function mredge_laplacian_snr_stable(info, prefs)
mredge_displacement_snr_stable % function mredge_laplacian_snr_stable(info, prefs)
mredge_laplacian_snr % function mredge_laplacian_snr(info, prefs)
mredge_laplacian_snr_stable % function mredge_laplacian_snr_stable(info, prefs)
mredge_masked_median Returns median of masked values for a parameter map
mredge_oss % function mredge_oss(info, prefs);
mredge_psf % function mredge_psf(info);
mredge_rer % function mredge_rer(info, prefs);
mredge_snr Calculates SNR maps and records SNR values in stats folder.
mredge_snr_stable % function mredge_laplacian_snr_stable(info, prefs)
mredge_springpot % function mredge_springpot(info, prefs);
mredge_springpot_stable % function mredge_springpot_stable(info, prefs);
mredge_springpot_stable_weighted % function mredge_springpot_stable_weighted(info, prefs);
mredge_whole_brain_median % function mredge_whole_brain_median(info, prefs);
mredge_z_xy_noise % function mredge_denoise(info, prefs);
SOURCE CODE
function mask = mredge_load_mask(info, prefs)
% Loads the anatomical mask image and returns as a 3D object
%
% INPUTS:
%
% info - an acquisition info structure created with make_acquisition_info
% prefs - preferences file created with mredge_prefs
%
% OUTPUTS:
%
% none
%
% Part of the MREdge software package
% Copyright (c) 2018 Eric Barnhill. All Rights Reserved
% So that we can vouch for results,
% this code is source-available but not open source.
% Please contact Eric Barnhill at ericbarnhill@protonmail.ch
% for permission to make modifications.
%
mask_vol = load_untouch_nii_eb(fullfile(mredge_analysis_path(info, prefs, 'magnitude'), 'magnitude_mask.nii'));
mask = mask_vol.img;