Description of daubf
Home > MREdge > functions > wavelet > stationary_dwt > daubf.m
daubf
PURPOSE
[h0, h1, g0, g1] = daubechies_filters(K)
SYNOPSIS
function [h0, h1, g0, g1] = daubf(K)
DESCRIPTION
 [h0, h1, g0, g1] = daubechies_filters(K)
 Dauechies wavelet filters of length N = 2K (K = 1...5)
 h0 - low-pass analysis filter
 h1 - high-pass analysis filter
 g0 - low-pass synthesis filter
 g1 - high-pass synthesis filter
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mad_est_3d
dtdenoise_z
dtdenoise_z_u
reverse_hard_thresh
zden_3D_DWT
dtdenoise_z_u
testing % TESTING MODULE
udwt_derivative_demo
udwt_example CONSTRUCT FILTERS
udwt_example_2
udwt_laplacian_demo
zden_3D_DWT
SOURCE CODE
function [h0, h1, g0, g1] = daubf(K)
% [h0, h1, g0, g1] = daubechies_filters(K)
% Dauechies wavelet filters of length N = 2K (K = 1...5)
%
% h0 - low-pass analysis filter
% h1 - high-pass analysis filter
% g0 - low-pass synthesis filter
% g1 - high-pass synthesis filter
switch K
    case 1
        c = [
            0.707106781186548   0.707106781186548   0.707106781186548  -0.707106781186548
            0.707106781186548  -0.707106781186548   0.707106781186548   0.707106781186548
            ];
    case 2
        c = [
            0.482962913144534  -0.129409522551260  -0.129409522551260  -0.482962913144534
            0.836516303737808  -0.224143868042013   0.224143868042013   0.836516303737808
            0.224143868042013   0.836516303737808   0.836516303737808  -0.224143868042013
            -0.129409522551260  -0.482962913144534   0.482962913144534  -0.129409522551260
            ];
    case 3
        c = [
            0.332670552950083   0.035226291885710   0.035226291885710  -0.332670552950083
            0.806891509311093   0.085441273882027  -0.085441273882027   0.806891509311093
            0.459877502118491  -0.135011020010255  -0.135011020010255  -0.459877502118491
            -0.135011020010255  -0.459877502118491   0.459877502118491  -0.135011020010255
            -0.085441273882027   0.806891509311093   0.806891509311093   0.085441273882027
            0.035226291885710  -0.332670552950083   0.332670552950083   0.035226291885710
            ];
    case 4
        c = [
            0.230377813308896  -0.010597401785069  -0.010597401785069  -0.230377813308896
            0.714846570552915  -0.032883011666885   0.032883011666885   0.714846570552915
            0.630880767929859   0.030841381835560   0.030841381835560  -0.630880767929859
            -0.027983769416859   0.187034811719093  -0.187034811719093  -0.027983769416859
            -0.187034811719093  -0.027983769416859  -0.027983769416859   0.187034811719093
            0.030841381835560  -0.630880767929859   0.630880767929859   0.030841381835560
            0.032883011666885   0.714846570552915   0.714846570552915  -0.032883011666885
            -0.010597401785069  -0.230377813308896   0.230377813308896  -0.010597401785069
            ];
    case 5
        c = [
            0.160102397974193   0.003335725285474   0.003335725285474  -0.160102397974193
            0.603829269797189   0.012580751999082  -0.012580751999082   0.603829269797189
            0.724308528437772  -0.006241490212798  -0.006241490212798  -0.724308528437772
            0.138428145901320  -0.077571493840046   0.077571493840046   0.138428145901320
            -0.242294887066382  -0.032244869584638  -0.032244869584638   0.242294887066382
            -0.032244869584638   0.242294887066382  -0.242294887066382  -0.032244869584638
            0.077571493840046   0.138428145901320   0.138428145901320  -0.077571493840046
            -0.006241490212798  -0.724308528437772   0.724308528437772  -0.006241490212798
            -0.012580751999082   0.603829269797189   0.603829269797189   0.012580751999082
            0.003335725285474  -0.160102397974193   0.160102397974193   0.003335725285474
            ];
end
h0 = c(:,1);    % low-pass analysis filter
h1 = c(:,2);    % high-pass analysis filter
g0 = c(:,3);    % low-pass synthesis filter
g1 = c(:,4);    % high-pass synthesis filter
end