Description of dtdenoise_3d_mad_ogs_undec
Home > MREdge > functions > wavelet > stationary_dwt > dtdenoise_3d_mad_ogs_undec.m
dtdenoise_3d_mad_ogs_undec
PURPOSE
3D Dualtree complex denoising
SYNOPSIS
function u_den = dtdenoise_3d_mad_ogs_undec(u, fac, J, mask)
DESCRIPTION
 3D Dualtree complex denoising
 with overlapping group sparsity thresholding
 also produces x y and z spatial derivatives
CROSS-REFERENCE INFORMATION
This function calls:
mad_est_3d
simplecrop
DT_OGS_u Dualtree complex denoising
DT_OGS_u Dualtree complex denoising
This function is called by:
sfwi_preprocess_stationary stacked frequency wave inversion
SOURCE CODE
function u_den = dtdenoise_3d_mad_ogs_undec(u, fac, J, mask)
% 3D Dualtree complex denoising
% with overlapping group sparsity thresholding
% also produces x y and z spatial derivatives
szu = size(u);
u_den = zeros(szu);
k = [3 3 3];
if numel(size(u)) < 4
    d4 = 1;
else
    d4 = size(u,4);
end
if nargin < 3
    mask = ones(size(u));
end
for n = 1:d4
    xr = real(u(:,:,:,n));
    xi = imag(u(:,:,:,n));
    sz = size(xr);
    mad_r = mad_est_3d(xr, mask);
    mad_i = mad_est_3d(xi, mask);
       lambda_r = (fac*mad_r);
    lambda_i = (fac*mad_i);
    xr = DT_OGS_u(xr, k, lambda_r, J);
    xi = DT_OGS_u(xi, k, lambda_i, J);
    u_den_vol = xr + 1i*xi;
    u_den(:,:,:,n) = simplecrop(u_den_vol, szu);
end