Description of iudwt3D
Home > MREdge > functions > wavelet > stationary_dwt > iudwt3D.m
iudwt3D
PURPOSE
Inverse Undecimated 3-D Discrete Wavelet Transform
SYNOPSIS
function y = iudwt3D(w, J, g0, g1)
DESCRIPTION
 Inverse Undecimated 3-D Discrete Wavelet Transform
 INPUT
   w : wavelet coefficient
   J : number of stages
   sf : synthesis filters
 OUTPUT:
   y : output array
 See: udwt3D, idwt3D
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
sfb3D_u 3D Synthesis Filter Bank
This function is called by:
reverse_hard_thresh
zden_3D_DWT
testing % TESTING MODULE
zden_3D_DWT
SOURCE CODE
function y = iudwt3D(w, J, g0, g1)
% Inverse Undecimated 3-D Discrete Wavelet Transform
%
% INPUT
%   w : wavelet coefficient
%   J : number of stages
%   sf : synthesis filters
%
% OUTPUT:
%   y : output array
%
% See: udwt3D, idwt3D
%
% WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
% http://taco.poly.edu/WaveletSoftware/
if nargin == 3
    sf = g0;
else
    sf = [g0 g1];
end
y = w{J+1};
for j = J:-1:1
   y = sfb3D_u(y, w{j}, j, sf, sf, sf);
end
m = numel(g0) - 1;
y = y(1:end-m, 1:end-m, 1:end-m);