Description of iudwt2D
Home > MREdge > functions > wavelet > stationary_dwt > iudwt2D.m
iudwt2D
PURPOSE
Inverse Undecimated 2-D Discrete Wavelet Transform
SYNOPSIS
function y = iudwt2D(w, J, g0, g1)
DESCRIPTION
 Inverse Undecimated 2-D Discrete Wavelet Transform
 INPUT
   w : wavelet coefficients
   J : number of stages
   sf : synthesis filters
 OUTPUT
   y : output array
 See: udwt2D, idwt2D
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
sfb2D_u Undecimated 2D Synthesis Filter Bank
This function is called by:
testing % TESTING MODULE
udwt_derivative_demo
udwt_laplacian_demo
SOURCE CODE
function y = iudwt2D(w, J, g0, g1)
% Inverse Undecimated 2-D Discrete Wavelet Transform
%
% INPUT
%   w : wavelet coefficients
%   J : number of stages
%   sf : synthesis filters
%
% OUTPUT
%   y : output array
%
% See: udwt2D, idwt2D
%
% WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
% http://taco.poly.edu/WaveletSoftware/
y = w{J+1}; % y is the lowpass
for j = J:-1:1
   y = sfb2D_u(y, w{j}, j, [g0, g1], [g0, g1]);
end
m = numel(g0) - 1;
y = y(1:end-m, 1:end-m);