Description of testing
Home > MREdge > functions > wavelet > stationary_dwt > testing.m
testing
PURPOSE
% TESTING MODULE
SYNOPSIS
This is a script file.
DESCRIPTION
% TESTING MODULE
CROSS-REFERENCE INFORMATION
This function calls:
daubf [h0, h1, g0, g1] = daubechies_filters(K)
udwt3D Undecimated 3-D Discrete Wavelet Transform
FSfarras Farras filters organized for the dual-tree
dualfilt1 Kingsbury Q-filters for the dual-tree complex DWT
cplxdual2D_u Dual-Tree Complex 2D Discrete Wavelet Transform
cplxdual3D_u 3D Complex Dual-Tree Discrete Wavelet Transform
daubf [h0, h1, g0, g1] = daubechies_filters(K)
icplxdual2D_u Inverse Dual-Tree Complex Undecimated 2D Discrete Wavelet Transform
icplxdual3D_u Inverse Dual-Tree Complex Undecimated 3D Discrete Wavelet Transform
iudwt2D Inverse Undecimated 2-D Discrete Wavelet Transform
iudwt3D Inverse Undecimated 3-D Discrete Wavelet Transform
udwt2D Undecimated 2-D Discrete Wavelet Transform
udwt3D Undecimated 3-D Discrete Wavelet Transform
This function is called by:
SOURCE CODE
%% TESTING MODULE
[Faf, Fsf] = FSfarras;
[af, sf] = dualfilt1;
[h0, h1, g0, g1] = daubf(3);
lena = double(imread('lena.tif'));
brain = load('brain');
brain = brain.brain;
%% 2D uDWT
disp('Testing 2D uDWT...');
tic
lena_udwt = iudwt2D(udwt2D(lena, 3, h0, h1), 3, g0, g1);
rmse = norm(lena_udwt(:) - lena(:)) / numel(brain(:));
disp(['RMSE: ', num2str(rmse)]);
toc
disp('--');
%% 2D uCDDWT
disp('Testing 2D uCDDWT...');
tic
lena_ucddwt = icplxdual2D_u(cplxdual2D_u(lena, 3, Faf, af), 3, Fsf, sf);
rmse = norm(lena_ucddwt(:) - lena(:)) / numel(brain(:));
disp(['RMSE: ', num2str(rmse)]);
toc
disp('--');
%% 3D uDWT
disp('Testing 3D uDWT...');
tic
brain_udwt = iudwt3D(udwt3D(brain, 3, h0, h1), 3, g0, g1);
rmse = norm(brain_udwt(:) - brain(:)) / numel(brain(:));
disp(['RMSE: ', num2str(rmse)]);
toc
disp('--');
%% 3D uCDDWT
disp('Testing 3D uCDDWT...');
tic
brain_ucddwt = icplxdual3D_u(cplxdual3D_u(brain, 3, Faf, af), 3, Fsf, sf);
rmse = norm(brain_ucddwt(:) - brain(:)) / numel(brain(:));
disp(['RMSE: ', num2str(rmse)]);
toc
disp('--')