Description of udwt_example_2
Home > MREdge > functions > wavelet > stationary_dwt > udwt_example_2.m
udwt_example_2
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
daubf [h0, h1, g0, g1] = daubechies_filters(K)
daubf [h0, h1, g0, g1] = daubechies_filters(K)
iudwt y = iudwt(w, J, g0, g1)
udwt Undecimated Discrete Wavelet Transform
This function is called by:
SOURCE CODE
for K = 1:4;
    % CONSTRUCT FILTERS
    [h0, h1, g0, g1] = daubf(K);
    % TEST PERFECT RECONSTRUCTION PROPERTY
    N = 779;
    x = rand(1,N);
    J = 5;
    w = udwt(x, J, h0, h1);
    y = iudwt(w, J, g0, g1);
    y = y(1:N);
    err = x - y;
    max(abs(err))
end