Description of cell2cat
Home > MREdge > functions > cell2cat.m
cell2cat
PURPOSE
SYNOPSIS
function y = cell2cat(x)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mad_est_3d
reverse_hard_thresh
zden_3D_DWT
zden_3D_DWT
SOURCE CODE
function y = cell2cat(x)
y = [];
for n = 1:numel(x)
    y = cat(3, y, x{n});
end