Description of dctn_octave
Home > MREdge > functions > dctn_octave.m
dctn_octave
PURPOSE
y = dctn(x)
SYNOPSIS
function y = dctn(x, dims)
DESCRIPTION
 y = dctn(x)
 Part of the MCNIT: M-code Complex and Nd Imaging Toolbox
 (c) Eric Barnhill 2016 All Rights Reserved.
 DESCRIPTION:
 N-dimensional discrete cosine transform.
 Requires no toolboxes -- uses Matlab-compatible modification of GNU octave DCT method
 INPUTS:
 x - 1+ dimensional object
 OUTPUTS:
 y - n-dimensional dct of the object
CROSS-REFERENCE INFORMATION
This function calls:
dct_octave dct_octave -- a Matlab-compatible modification of GNU Octave's dct. Created December 2016.
resh y = reshape(x,d)
This function is called by:
dct_unwrap
SOURCE CODE
function y = dctn(x, dims)
% y = dctn(x)
% Part of the MCNIT: M-code Complex and Nd Imaging Toolbox
% (c) Eric Barnhill 2016 All Rights Reserved.
%
% DESCRIPTION:
%
% N-dimensional discrete cosine transform.
% Requires no toolboxes -- uses Matlab-compatible modification of GNU octave DCT method
%
% INPUTS:
%
% x - 1+ dimensional object
%
% OUTPUTS:
%
% y - n-dimensional dct of the object
if nargin < 2
    dims = ndims(x);
end
rem_dims = ndims(x) - dims;
for d = 1:dims
    sz = size(x);
    [x_resh, num_cols] = resh(x, 2);
    for n = 1:num_cols
        x_resh(:,n) = dct_octave(x_resh(:,n));
    end
    x = reshape(x_resh, sz);
    x = shiftdim(x, 1);
end
y = shiftdim(x, rem_dims);