Description of load_untouch_nii_eb
Home > MREdge > functions > load_untouch_nii_eb.m
load_untouch_nii_eb
PURPOSE
Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
SYNOPSIS
function nii = load_untouch_nii_eb(filename, img_idx, dim5_idx, dim6_idx, dim7_idx,old_RGB, slice_idx)
DESCRIPTION
  Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
  geometric transform or voxel intensity scaling.
  Although according to NIFTI website, all those header information are
  supposed to be applied to the loaded NIFTI image, there are some
  situations that people do want to leave the original NIFTI header and
  data untouched. They will probably just use MATLAB to do certain image
  processing regardless of image orientation, and to save data back with
  the same NIfTI header.
  Since this program is only served for those situations, please use it
  together with "save_untouch_nii.m", and do not use "save_nii.m" or
  "view_nii.m" for the data that is loaded by "load_untouch_nii.m". For
  normal situation, you should use "load_nii.m" instead.
  Usage: nii = load_untouch_nii(filename, [img_idx], [dim5_idx], [dim6_idx], ...
            [dim7_idx], [old_RGB], [slice_idx])
  filename  -     NIFTI or ANALYZE file name.
  img_idx (optional)  -  a numerical array of image volume indices.
    Only the specified volumes will be loaded. All available image
    volumes will be loaded, if it is default or empty.
    The number of images scans can be obtained from get_nii_frame.m,
    or simply: hdr.dime.dim(5).
  dim5_idx (optional)  -  a numerical array of 5th dimension indices.
    Only the specified range will be loaded. All available range
    will be loaded, if it is default or empty.
  dim6_idx (optional)  -  a numerical array of 6th dimension indices.
    Only the specified range will be loaded. All available range
    will be loaded, if it is default or empty.
  dim7_idx (optional)  -  a numerical array of 7th dimension indices.
    Only the specified range will be loaded. All available range
    will be loaded, if it is default or empty.
  old_RGB (optional)  -  a scale number to tell difference of new RGB24
    from old RGB24. New RGB24 uses RGB triple sequentially for each
    voxel, like [R1 G1 B1 R2 G2 B2 ...]. Analyze 6.0 from AnalyzeDirect
    uses old RGB24, in a way like [R1 R2 ... G1 G2 ... B1 B2 ...] for
    each slices. If the image that you view is garbled, try to set
    old_RGB variable to 1 and try again, because it could be in
    old RGB24. It will be set to 0, if it is default or empty.
  slice_idx (optional)  -  a numerical array of image slice indices.
    Only the specified slices will be loaded. All available image
    slices will be loaded, if it is default or empty.
  Returned values:
  nii structure:
    hdr -        struct with NIFTI header fields.
    filetype -    Analyze format .hdr/.img (0);
            NIFTI .hdr/.img (1);
            NIFTI .nii (2)
    fileprefix -     NIFTI filename without extension.
    machine -     machine string variable.
    img -         3D (or 4D) matrix of NIFTI data.
  - Jimmy Shen (jimmy@rotman-baycrest.on.ca)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mredge_break_into_frequencies For acquisitions with the all_frequencies_one_series flag, partitions the time series by frequency
mredge_fd_import
mredge_get_placeholder_from_phase
mredge_load_FT_as_5d Load Fourier-transformed wavefield into MATLAB.
mredge_load_magnitude_as_6d % function mredge_laplacian_snr(info, prefs)
mredge_load_phase_as_6d % function mredge_load_phase_as_6d(info, prefs)
mredge_rename_by_frequency For acquisitions where each frequency has its own series number, rename each series to its corresponding frequency.
mredge_save_5d_as_FT
mredge_sort_time_steps
mredge_split_4d Splits a 4D NIfTI into 3D images and passes the list of the 3d image paths. For FSL and SPM applications.
loop_over_freqs_and_components_4d_nii loop_over_freqs_and_components_4d_nii(info, prefs, fun, IN_DIR_descr, OUT_DIR_descr)
mredge_aniso_diff % function mredge_aniso_diff(info, prefs);
mredge_average_magnitude Creates a single, averaged t2 magnitude map from an MRE acquisition, the preferred volume to use for co-registration and segmentation.
mredge_bandpass Applies highpass and lowpass butterworth filters if they are set in prefs
mredge_denoise Denoise Fourier-transformed wavefield.
mredge_denoise_nopar % function mredge_denoise_nopar(info, prefs);
mredge_denoise_raw Denoises raw complex data prior to phase unwrapping
mredge_ft2double % function mredge_ft2double(info,prefs);
mredge_gaussian % function mredge_gaussian(info, prefs);
mredge_invert Wave inversion of preprocessed MRE data
mredge_load_mask Loads the anatomical mask image and returns as a 3D object
mredge_mag2double Converts values in magnitude NIfTI objects to double type, to avoid type conflicts.
mredge_motion_correction_spm Performs motion correction using SPM. Requires SPM 12.
mredge_normalize_phase Normalizes phase data to [0, 2pi) .
mredge_normalize_phase_prelude % function mredge_normalize_phase(info, prefs);
mredge_phase2double Converts values in phase NIfTI objects to double type, to avoid type conflicts.
mredge_phase_unwrap Applies phase unwrapping methods.
mredge_pm2ri Converts phase and magnitude data to real and imaginary data for processing of complex MR signal
mredge_raw_denoise
mredge_remove_divergence Numerical divergence removal of the wave field
mredge_remove_ipds Removes interslice phase discontinuities.
mredge_ri2pm Converts real and imagianry data to phase and magnitude
mredge_slice_align Dejitters slices using adaptation of Nikolova et al 2001 dejitter algorithm
mredge_temporal_ft Temporally Fourier-transforms the complex wave field.
mredge_zden % function mredge_denoise(info, prefs);
mredge_avg_mag_to_mni Co-registers magnitude image to MNI space. The deformation map is then used to co-register all elasticity maps.
mredge_coreg_param_to_mni Coregisters a parameter map to MNI space using the deformation map from the averaged magnitude.
mredge_coreg_param_to_mni_sliding % function coreg_param_to_mni_sliding(info, param)
mredge_label_param_map Labels paramater map results and produces statistics for brain anatomical regions.
mredge_label_param_map_sliding % function stats = mredge_label_param_map_sliding(info, param)
mredge_label_param_map_springpot % function stats = mredge_label_param_map(info, param)
mredge_label_param_map_stable % function stats = mredge_label_param_map_stable(info, param)
mredge_amp_wave_snr % function mredge_amp_guided_wave_to_noise(info, prefs);
mredge_amplitudes Creates summed amplitude images
mredge_amplitudes_sliding % function mredge_stable_amplitudes(info, prefs);
mredge_cortical_average % function mredge_cortical_average(info, prefs);
mredge_cortical_median % function mredge_cortical_median(info, prefs);
mredge_cortical_median_stable % function mredge_cortical_median(info, prefs);
mredge_displacement_snr % function mredge_laplacian_snr_stable(info, prefs)
mredge_displacement_snr_stable % function mredge_laplacian_snr_stable(info, prefs)
mredge_laplacian_snr % function mredge_laplacian_snr(info, prefs)
mredge_laplacian_snr_stable % function mredge_laplacian_snr_stable(info, prefs)
mredge_masked_median Returns median of masked values for a parameter map
mredge_oss % function mredge_oss(info, prefs);
mredge_psf % function mredge_psf(info);
mredge_rer % function mredge_rer(info, prefs);
mredge_snr Calculates SNR maps and records SNR values in stats folder.
mredge_springpot % function mredge_springpot(info, prefs);
mredge_springpot_stable % function mredge_springpot_stable(info, prefs);
mredge_springpot_stable_weighted % function mredge_springpot_stable_weighted(info, prefs);
mredge_stable_amplitudes % function mredge_stable_amplitudes(info, prefs);
mredge_whole_brain_median % function mredge_whole_brain_median(info, prefs);
mredge_z_discontinuities % function mredge_denoise(info, prefs);
mredge_z_xy_noise % function mredge_denoise(info, prefs);
SOURCE CODE
%  Load NIFTI or ANALYZE dataset, but not applying any appropriate affine
%  geometric transform or voxel intensity scaling.
%
%  Although according to NIFTI website, all those header information are
%  supposed to be applied to the loaded NIFTI image, there are some
%  situations that people do want to leave the original NIFTI header and
%  data untouched. They will probably just use MATLAB to do certain image
%  processing regardless of image orientation, and to save data back with
%  the same NIfTI header.
%
%  Since this program is only served for those situations, please use it
%  together with "save_untouch_nii.m", and do not use "save_nii.m" or
%  "view_nii.m" for the data that is loaded by "load_untouch_nii.m". For
%  normal situation, you should use "load_nii.m" instead.
%
%  Usage: nii = load_untouch_nii(filename, [img_idx], [dim5_idx], [dim6_idx], ...
%            [dim7_idx], [old_RGB], [slice_idx])
%
%  filename  -     NIFTI or ANALYZE file name.
%
%  img_idx (optional)  -  a numerical array of image volume indices.
%    Only the specified volumes will be loaded. All available image
%    volumes will be loaded, if it is default or empty.
%
%    The number of images scans can be obtained from get_nii_frame.m,
%    or simply: hdr.dime.dim(5).
%
%  dim5_idx (optional)  -  a numerical array of 5th dimension indices.
%    Only the specified range will be loaded. All available range
%    will be loaded, if it is default or empty.
%
%  dim6_idx (optional)  -  a numerical array of 6th dimension indices.
%    Only the specified range will be loaded. All available range
%    will be loaded, if it is default or empty.
%
%  dim7_idx (optional)  -  a numerical array of 7th dimension indices.
%    Only the specified range will be loaded. All available range
%    will be loaded, if it is default or empty.
%
%  old_RGB (optional)  -  a scale number to tell difference of new RGB24
%    from old RGB24. New RGB24 uses RGB triple sequentially for each
%    voxel, like [R1 G1 B1 R2 G2 B2 ...]. Analyze 6.0 from AnalyzeDirect
%    uses old RGB24, in a way like [R1 R2 ... G1 G2 ... B1 B2 ...] for
%    each slices. If the image that you view is garbled, try to set
%    old_RGB variable to 1 and try again, because it could be in
%    old RGB24. It will be set to 0, if it is default or empty.
%
%  slice_idx (optional)  -  a numerical array of image slice indices.
%    Only the specified slices will be loaded. All available image
%    slices will be loaded, if it is default or empty.
%
%  Returned values:
%
%  nii structure:
%
%    hdr -        struct with NIFTI header fields.
%
%    filetype -    Analyze format .hdr/.img (0);
%            NIFTI .hdr/.img (1);
%            NIFTI .nii (2)
%
%    fileprefix -     NIFTI filename without extension.
%
%    machine -     machine string variable.
%
%    img -         3D (or 4D) matrix of NIFTI data.
%
%  - Jimmy Shen (jimmy@rotman-baycrest.on.ca)
%
function nii = load_untouch_nii_eb(filename, img_idx, dim5_idx, dim6_idx, dim7_idx, ...
            old_RGB, slice_idx)
   if nargin == 1
    img_idx = [];
    dim5_idx = [];
    dim6_idx = [];
    dim7_idx = [];
    old_RGB = [];
    slice_idx = [];
   end
   if ~exist('filename','var')
      error('Usage: nii = load_untouch_nii(filename, [img_idx], [dim5_idx], [dim6_idx], [dim7_idx], [old_RGB], [slice_idx])');
   end
   if ~exist('img_idx','var') | isempty(img_idx)
      img_idx = [];
   end
   if ~exist('dim5_idx','var') | isempty(dim5_idx)
      dim5_idx = [];
   end
   if ~exist('dim6_idx','var') | isempty(dim6_idx)
      dim6_idx = [];
   end
   if ~exist('dim7_idx','var') | isempty(dim7_idx)
      dim7_idx = [];
   end
   if ~exist('old_RGB','var') | isempty(old_RGB)
      old_RGB = 0;
   end
   if ~exist('slice_idx','var') | isempty(slice_idx)
      slice_idx = [];
   end
   v = version;
   %  Check file extension. If .gz, unpack it into temp folder
   %
   if length(filename) > 2 & strcmp(filename(end-2:end), '.gz')
      if ~strcmp(filename(end-6:end), '.img.gz') & ...
     ~strcmp(filename(end-6:end), '.hdr.gz') & ...
     ~strcmp(filename(end-6:end), '.nii.gz')
         error('Please check filename.');
      end
      %{
      if str2num(v(1:3)) < 7.1 | ~usejava('jvm')
         error('Please use MATLAB 7.1 (with java) and above, or run gunzip outside MATLAB.');
      elseif strcmp(filename(end-6:end), '.img.gz')
      %}
      if strcmp(filename(end-6:end), '.img.gz')
         filename1 = filename;
         filename2 = filename;
         filename2(end-6:end) = '';
         filename2 = [filename2, '.hdr.gz'];
         tmpDir = tempname;
         mkdir(tmpDir);
         gzFileName = filename;
         filename1 = gunzip(filename1, tmpDir);
         filename2 = gunzip(filename2, tmpDir);
         filename = char(filename1);    % convert from cell to string
      elseif strcmp(filename(end-6:end), '.hdr.gz')
         filename1 = filename;
         filename2 = filename;
         filename2(end-6:end) = '';
         filename2 = [filename2, '.img.gz'];
         tmpDir = tempname;
         mkdir(tmpDir);
         gzFileName = filename;
         filename1 = gunzip(filename1, tmpDir);
         filename2 = gunzip(filename2, tmpDir);
         filename = char(filename1);    % convert from cell to string
      elseif strcmp(filename(end-6:end), '.nii.gz')
         tmpDir = tempname;
         mkdir(tmpDir);
         gzFileName = filename;
         filename = gunzip(filename, tmpDir);
         filename = char(filename);    % convert from cell to string
      end
   end
   %  Read the dataset header
   %
   [nii.hdr,nii.filetype,nii.fileprefix,nii.machine] = load_nii_hdr(filename);
   if nii.filetype == 0
      nii.hdr = load_untouch0_nii_hdr(nii.fileprefix,nii.machine);
      nii.ext = [];
   else
      nii.hdr = load_untouch_nii_hdr(nii.fileprefix,nii.machine,nii.filetype);
      %  Read the header extension
      %
      nii.ext = load_nii_ext(filename);
   end
   %  Read the dataset body
   %
   [nii.img,nii.hdr] = load_untouch_nii_img(nii.hdr,nii.filetype,nii.fileprefix, ...
        nii.machine,img_idx,dim5_idx,dim6_idx,dim7_idx,old_RGB,slice_idx);
   %  Perform some of sform/qform transform
   %
%   nii = xform_nii(nii, tolerance, preferredForm);
   nii.untouch = 1;
   %  Clean up after gunzip
   %
   if exist('gzFileName', 'var')
      %  fix fileprefix so it doesn't point to temp location
      %
      nii.fileprefix = gzFileName(1:end-7);
      rmdir(tmpDir,'s');
   end
   return                    % load_untouch_nii