Description of mad_est_3d
Home > MREdge > functions > mad_est_3d.m
mad_est_3d
PURPOSE
SYNOPSIS
function sigma = mad_est_3d(volume, mask)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
cell2cat
daubf [h0, h1, g0, g1] = daubechies_filters(K)
simplecrop
udwt3D Undecimated 3-D Discrete Wavelet Transform
daubf [h0, h1, g0, g1] = daubechies_filters(K)
udwt3D Undecimated 3-D Discrete Wavelet Transform
This function is called by:
DT_3D_v0_51b Dualtree complex denoising
DT_3D_v0_51g Dualtree complex denoising
dtdenoise_3d_mad Dualtree complex denoising
dtdenoise_3d_mad_ogs_undec_diff 3D Dualtree complex denoising
dtdenoise_xy_pca_mad
dtdenoise_xy_pca_mad_amp
dtdenoise_xy_pca_mad_u
dtdenoise_3d_mad_ogs_undec 3D Dualtree complex denoising
dtdenoise_3d_mad_ogs_undec_diff 3D Dualtree complex denoising
mredge_denoise_3d % function y = mredge_denoise_3d(x, info, prefs)
mredge_displacement_snr % function mredge_laplacian_snr_stable(info, prefs)
mredge_displacement_snr_stable % function mredge_laplacian_snr_stable(info, prefs)
mredge_laplacian_snr_stable % function mredge_laplacian_snr_stable(info, prefs)
mredge_snr_stable % function mredge_laplacian_snr_stable(info, prefs)
mredge_z_xy_noise % function mredge_denoise(info, prefs);
SOURCE CODE
function sigma = mad_est_3d(volume, mask)
if nargin < 2
    mask = ones(size(vec(volume)));
end
sz = size(volume);
[h0, h1, g0, g1] = daubf(3);
af = [h0 h1];
w = udwt3D(volume, 1, af);
coef_cat = cell2cat(w{1});
coef_cat = reshape(coef_cat, [size(coef_cat, 1), size(coef_cat, 2), size(coef_cat, 3)/7, 7]);
coef_cat = vec(simplecrop(coef_cat, [sz(1) sz(2) sz(3) 7]));
mask_cat = vec(repmat(mask, [1 1 1 7]));
% mask
volvec = coef_cat .* mask_cat;
% kill nan
volvec(isnan(volvec)) = 0;
% exclude zero
volvec_nonzero = volvec(volvec ~= 0);
volvec_median = median(real(volvec_nonzero));
sigma = median(abs(volvec_nonzero - volvec_median));