Description of normalizeImage
Home > MREdge > functions > normalizeImage.m
normalizeImage
PURPOSE
SYNOPSIS
function [ y ] = normalise(x)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mredge_est_mad
mredge_normalize_phase Normalizes phase data to [0, 2pi) .
mredge_normalize_phase_prelude % function mredge_normalize_phase(info, prefs);
mredge_phase_unwrap Applies phase unwrapping methods.
SOURCE CODE
function [ y ] = normalise(x)
mn = min(x(:));
mx = max(x(:));
y = (x - mn) ./ (mx-mn);
end