Description of signal_power
Home > MREdge > functions > signal_power.m
signal_power
PURPOSE
SYNOPSIS
function p = signal_power(signal, mask)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mredge_displacement_snr % function mredge_laplacian_snr_stable(info, prefs)
mredge_displacement_snr_stable % function mredge_laplacian_snr_stable(info, prefs)
mredge_laplacian_snr % function mredge_laplacian_snr(info, prefs)
mredge_laplacian_snr_stable % function mredge_laplacian_snr_stable(info, prefs)
mredge_snr_stable % function mredge_laplacian_snr_stable(info, prefs)
mredge_z_xy_noise % function mredge_denoise(info, prefs);
SOURCE CODE
function p = signal_power(signal, mask)
if nargin == 1
    mask = ones(size(signal));
end
p = sum(abs(signal(mask==1)).^2)/length(signal(mask==1));