Description of simplecrop
Home > MREdge > functions > simplecrop.m
simplecrop
PURPOSE
SYNOPSIS
function v = simplecrop(w, cropdims)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mad_est_3d
cdwt_diff_2D if 2d, needless to say Z is rubbish
cdwt_diff_2D_stationary if 2d, needless to say Z is rubbish
cdwt_diff_3D
cdwt_diff_ogs_2D if 2d, needless to say Z is rubbish
cdwt_laplacian
dtdenoise_3d_mad_ogs_undec 3D Dualtree complex denoising
dtdenoise_3d_mad_ogs_undec_diff 3D Dualtree complex denoising
dtdenoise_3d_mad_ogs_undec_log 3D Dualtree complex denoising
dtdenoise_3d_pca
reverse_hard_thresh
zden_3D_DWT
dtdenoise_3d_asg 3D Dualtree complex denoising
dtdenoise_3d_mad_ogs_undec 3D Dualtree complex denoising
dtdenoise_3d_mad_ogs_undec_diff 3D Dualtree complex denoising
wavelet_gradients_stationary
zden_3D_DWT
mredge_masked_median Returns median of masked values for a parameter map
SOURCE CODE
function v = simplecrop(w, cropdims)
    if ndims(w) == 1
        v = w(1:cropdims(1));
    elseif ndims(w) == 2
        v = w(1:cropdims(1), 1:cropdims(2));
    elseif ndims(w) == 3
        v = w(1:cropdims(1), 1:cropdims(2), 1:cropdims(3));
    elseif ndims(w) == 4
        v = w(1:cropdims(1), 1:cropdims(2), 1:cropdims(3), 1:cropdims(4));
    end
end